version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - api
    environment:
      NEST_API_URL: http://api:4000
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      API_PORT: 4000
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: futurerealm_sms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
