/**
 * Real geographic/administrative reference data for the onboarding wizard's country and
 * region pickers. Each entry is [first-level division label, second-level division label,
 * a plain description of the two registration-number fields for that country, and the
 * country's actual first-level divisions]. Picking a country re-labels the fields beneath
 * it, so a school in Nairobi is asked for a County and a Sub-county, never an LGA.
 *
 * This is factual public reference data (country subdivision names, standard registration
 * scheme labels) — not a claim that this system validates or enforces any of it beyond
 * Nigeria (see NIGERIA_PHONE_PATTERN / computeRiskAssessment in the onboarding backend).
 */
export interface CountryGeo {
  level1Label: string;
  level2Label: string;
  registrationLabel1: string;
  registrationLabel2: string;
  divisions: string[];
}

export const OTHER_COUNTRY = "Other — not listed";

export const COUNTRY_GEO: Record<string, CountryGeo> = {
  Nigeria: { level1Label: "State", level2Label: "LGA", registrationLabel1: "CAC registration number", registrationLabel2: "Ministry of Education approval number", divisions: ["Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno", "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "FCT Abuja", "Gombe", "Imo", "Jigawa", "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara"] },
  Ghana: { level1Label: "Region", level2Label: "District", registrationLabel1: "Registrar-General registration number", registrationLabel2: "GES approval number", divisions: ["Ahafo", "Ashanti", "Bono", "Bono East", "Central", "Eastern", "Greater Accra", "North East", "Northern", "Oti", "Savannah", "Upper East", "Upper West", "Volta", "Western", "Western North"] },
  Kenya: { level1Label: "County", level2Label: "Sub-county", registrationLabel1: "Business registration number", registrationLabel2: "MoE registration number", divisions: ["Baringo", "Bomet", "Bungoma", "Busia", "Elgeyo-Marakwet", "Embu", "Garissa", "Homa Bay", "Isiolo", "Kajiado", "Kakamega", "Kericho", "Kiambu", "Kilifi", "Kirinyaga", "Kisii", "Kisumu", "Kitui", "Kwale", "Laikipia", "Lamu", "Machakos", "Makueni", "Mandera", "Marsabit", "Meru", "Migori", "Mombasa", "Murang’a", "Nairobi", "Nakuru", "Nandi", "Narok", "Nyamira", "Nyandarua", "Nyeri", "Samburu", "Siaya", "Taita-Taveta", "Tana River", "Tharaka-Nithi", "Trans Nzoia", "Turkana", "Uasin Gishu", "Vihiga", "Wajir", "West Pokot"] },
  "South Africa": { level1Label: "Province", level2Label: "Municipality", registrationLabel1: "CIPC registration number", registrationLabel2: "DBE registration number", divisions: ["Eastern Cape", "Free State", "Gauteng", "KwaZulu-Natal", "Limpopo", "Mpumalanga", "North West", "Northern Cape", "Western Cape"] },
  Tanzania: { level1Label: "Region", level2Label: "District", registrationLabel1: "BRELA registration number", registrationLabel2: "MoEST registration number", divisions: ["Arusha", "Dar es Salaam", "Dodoma", "Geita", "Iringa", "Kagera", "Katavi", "Kigoma", "Kilimanjaro", "Lindi", "Manyara", "Mara", "Mbeya", "Morogoro", "Mtwara", "Mwanza", "Njombe", "Pemba North", "Pemba South", "Pwani", "Rukwa", "Ruvuma", "Shinyanga", "Simiyu", "Singida", "Songwe", "Tabora", "Tanga", "Zanzibar North", "Zanzibar South", "Zanzibar Urban"] },
  Uganda: { level1Label: "Region", level2Label: "District", registrationLabel1: "URSB registration number", registrationLabel2: "MoES licence number", divisions: ["Central", "Eastern", "Northern", "Western"] },
  Rwanda: { level1Label: "Province", level2Label: "District", registrationLabel1: "RDB registration number", registrationLabel2: "MINEDUC approval number", divisions: ["Kigali City", "Eastern", "Northern", "Southern", "Western"] },
  Zambia: { level1Label: "Province", level2Label: "District", registrationLabel1: "PACRA registration number", registrationLabel2: "MoGE registration number", divisions: ["Central", "Copperbelt", "Eastern", "Luapula", "Lusaka", "Muchinga", "North-Western", "Northern", "Southern", "Western"] },
  Zimbabwe: { level1Label: "Province", level2Label: "District", registrationLabel1: "Company registration number", registrationLabel2: "MoPSE registration number", divisions: ["Bulawayo", "Harare", "Manicaland", "Mashonaland Central", "Mashonaland East", "Mashonaland West", "Masvingo", "Matabeleland North", "Matabeleland South", "Midlands"] },
  Botswana: { level1Label: "District", level2Label: "Sub-district", registrationLabel1: "CIPA registration number", registrationLabel2: "MoBE registration number", divisions: ["Central", "Chobe", "Francistown", "Gaborone", "Ghanzi", "Kgalagadi", "Kgatleng", "Kweneng", "Lobatse", "North East", "North West", "Selibe Phikwe", "South East", "Southern"] },
  Namibia: { level1Label: "Region", level2Label: "Constituency", registrationLabel1: "BIPA registration number", registrationLabel2: "MoEAC registration number", divisions: ["Erongo", "Hardap", "ǀKaras", "Kavango East", "Kavango West", "Khomas", "Kunene", "Ohangwena", "Omaheke", "Omusati", "Oshana", "Oshikoto", "Otjozondjupa", "Zambezi"] },
  Ethiopia: { level1Label: "Region", level2Label: "Zone", registrationLabel1: "Trade licence number", registrationLabel2: "MoE approval number", divisions: ["Addis Ababa", "Afar", "Amhara", "Benishangul-Gumuz", "Central Ethiopia", "Dire Dawa", "Gambela", "Harari", "Oromia", "Sidama", "Somali", "South Ethiopia", "South West Ethiopia", "Tigray"] },
  Egypt: { level1Label: "Governorate", level2Label: "District", registrationLabel1: "Commercial registry number", registrationLabel2: "MoE licence number", divisions: ["Alexandria", "Aswan", "Asyut", "Beheira", "Beni Suef", "Cairo", "Dakahlia", "Damietta", "Faiyum", "Gharbia", "Giza", "Ismailia", "Kafr El Sheikh", "Luxor", "Matrouh", "Minya", "Monufia", "New Valley", "North Sinai", "Port Said", "Qalyubia", "Qena", "Red Sea", "Sharqia", "Sohag", "South Sinai", "Suez"] },
  Morocco: { level1Label: "Region", level2Label: "Province", registrationLabel1: "Commercial registry number", registrationLabel2: "MEN authorisation number", divisions: ["Béni Mellal-Khénifra", "Casablanca-Settat", "Dakhla-Oued Ed-Dahab", "Drâa-Tafilalet", "Fès-Meknès", "Guelmim-Oued Noun", "Laâyoune-Sakia El Hamra", "Marrakesh-Safi", "Oriental", "Rabat-Salé-Kénitra", "Souss-Massa", "Tanger-Tétouan-Al Hoceïma"] },
  Cameroon: { level1Label: "Region", level2Label: "Division", registrationLabel1: "RCCM registration number", registrationLabel2: "MINEDUB / MINESEC approval number", divisions: ["Adamawa", "Centre", "East", "Far North", "Littoral", "North", "North-West", "South", "South-West", "West"] },
  "Côte d’Ivoire": { level1Label: "District", level2Label: "Department", registrationLabel1: "RCCM registration number", registrationLabel2: "MENA approval number", divisions: ["Abidjan", "Bas-Sassandra", "Comoé", "Denguélé", "Gôh-Djiboua", "Lacs", "Lagunes", "Montagnes", "Sassandra-Marahoué", "Savanes", "Vallée du Bandama", "Woroba", "Yamoussoukro", "Zanzan"] },
  Senegal: { level1Label: "Region", level2Label: "Department", registrationLabel1: "RCCM registration number", registrationLabel2: "MEN approval number", divisions: ["Dakar", "Diourbel", "Fatick", "Kaffrine", "Kaolack", "Kédougou", "Kolda", "Louga", "Matam", "Saint-Louis", "Sédhiou", "Tambacounda", "Thiès", "Ziguinchor"] },
  "Sierra Leone": { level1Label: "Province", level2Label: "District", registrationLabel1: "Company registration number", registrationLabel2: "MBSSE approval number", divisions: ["Eastern", "North West", "Northern", "Southern", "Western Area"] },
  Liberia: { level1Label: "County", level2Label: "District", registrationLabel1: "Business registration number", registrationLabel2: "MoE approval number", divisions: ["Bomi", "Bong", "Gbarpolu", "Grand Bassa", "Grand Cape Mount", "Grand Gedeh", "Grand Kru", "Lofa", "Margibi", "Maryland", "Montserrado", "Nimba", "River Cess", "River Gee", "Sinoe"] },
  Gambia: { level1Label: "Region", level2Label: "District", registrationLabel1: "Business registration number", registrationLabel2: "MoBSE approval number", divisions: ["Banjul", "Central River", "Lower River", "North Bank", "Upper River", "West Coast"] },
  "United Arab Emirates": { level1Label: "Emirate", level2Label: "Area", registrationLabel1: "Trade licence number", registrationLabel2: "KHDA / ADEK permit number", divisions: ["Abu Dhabi", "Ajman", "Dubai", "Fujairah", "Ras Al Khaimah", "Sharjah", "Umm Al Quwain"] },
  "Saudi Arabia": { level1Label: "Region", level2Label: "Governorate", registrationLabel1: "Commercial registration number", registrationLabel2: "MoE licence number", divisions: ["Al Bahah", "Al Jawf", "Asir", "Eastern Province", "Ha’il", "Jazan", "Madinah", "Makkah", "Najran", "Northern Borders", "Qassim", "Riyadh", "Tabuk"] },
  Qatar: { level1Label: "Municipality", level2Label: "Zone", registrationLabel1: "Commercial registration number", registrationLabel2: "MoEHE licence number", divisions: ["Al Daayen", "Al Khor", "Al Rayyan", "Al Shahaniya", "Al Wakrah", "Doha", "Madinat ash Shamal", "Umm Salal"] },
  Oman: { level1Label: "Governorate", level2Label: "Wilayat", registrationLabel1: "Commercial registration number", registrationLabel2: "MoE licence number", divisions: ["Ad Dakhiliyah", "Ad Dhahirah", "Al Batinah North", "Al Batinah South", "Al Buraimi", "Al Wusta", "Ash Sharqiyah North", "Ash Sharqiyah South", "Dhofar", "Muscat", "Musandam"] },
  India: { level1Label: "State / UT", level2Label: "District", registrationLabel1: "Society / Trust registration number", registrationLabel2: "Board affiliation number", divisions: ["Andaman and Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chandigarh", "Chhattisgarh", "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka", "Kerala", "Ladakh", "Lakshadweep", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Puducherry", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"] },
  Pakistan: { level1Label: "Province", level2Label: "District", registrationLabel1: "SECP registration number", registrationLabel2: "Board affiliation number", divisions: ["Azad Jammu and Kashmir", "Balochistan", "Gilgit-Baltistan", "Islamabad Capital Territory", "Khyber Pakhtunkhwa", "Punjab", "Sindh"] },
  Bangladesh: { level1Label: "Division", level2Label: "District", registrationLabel1: "RJSC registration number", registrationLabel2: "Board / EIIN number", divisions: ["Barishal", "Chattogram", "Dhaka", "Khulna", "Mymensingh", "Rajshahi", "Rangpur", "Sylhet"] },
  "Sri Lanka": { level1Label: "Province", level2Label: "District", registrationLabel1: "Company registration number", registrationLabel2: "MoE registration number", divisions: ["Central", "Eastern", "North Central", "North Western", "Northern", "Sabaragamuwa", "Southern", "Uva", "Western"] },
  Nepal: { level1Label: "Province", level2Label: "District", registrationLabel1: "Company registration number", registrationLabel2: "MoEST approval number", divisions: ["Bagmati", "Gandaki", "Karnali", "Koshi", "Lumbini", "Madhesh", "Sudurpashchim"] },
  Malaysia: { level1Label: "State", level2Label: "District", registrationLabel1: "SSM registration number", registrationLabel2: "MoE registration number", divisions: ["Johor", "Kedah", "Kelantan", "Kuala Lumpur", "Labuan", "Melaka", "Negeri Sembilan", "Pahang", "Penang", "Perak", "Perlis", "Putrajaya", "Sabah", "Sarawak", "Selangor", "Terengganu"] },
  Singapore: { level1Label: "Region", level2Label: "Planning area", registrationLabel1: "ACRA registration number", registrationLabel2: "MoE / CPE registration number", divisions: ["Central", "East", "North", "North-East", "West"] },
  Indonesia: { level1Label: "Province", level2Label: "Regency", registrationLabel1: "Company registration number", registrationLabel2: "NPSN school number", divisions: ["Aceh", "Bali", "Bangka Belitung", "Banten", "Bengkulu", "Central Java", "Central Kalimantan", "Central Sulawesi", "East Java", "East Kalimantan", "East Nusa Tenggara", "Gorontalo", "Jakarta", "Jambi", "Lampung", "Maluku", "North Kalimantan", "North Maluku", "North Sulawesi", "North Sumatra", "Papua", "Riau", "Riau Islands", "South Kalimantan", "South Sulawesi", "South Sumatra", "Southeast Sulawesi", "West Java", "West Kalimantan", "West Nusa Tenggara", "West Papua", "West Sulawesi", "West Sumatra", "Yogyakarta"] },
  Philippines: { level1Label: "Region", level2Label: "Province", registrationLabel1: "SEC registration number", registrationLabel2: "DepEd permit number", divisions: ["Bangsamoro", "Bicol", "Cagayan Valley", "Calabarzon", "Caraga", "Central Luzon", "Central Visayas", "Cordillera", "Davao", "Eastern Visayas", "Ilocos", "Metro Manila", "Mimaropa", "Northern Mindanao", "Soccsksargen", "Western Visayas", "Zamboanga Peninsula"] },
  "United Kingdom": { level1Label: "Nation / Region", level2Label: "Local authority", registrationLabel1: "Companies House number", registrationLabel2: "DfE URN", divisions: ["England", "Northern Ireland", "Scotland", "Wales"] },
  Ireland: { level1Label: "County", level2Label: "District", registrationLabel1: "CRO registration number", registrationLabel2: "Department of Education roll number", divisions: ["Carlow", "Cavan", "Clare", "Cork", "Donegal", "Dublin", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Waterford", "Westmeath", "Wexford", "Wicklow"] },
  "United States": { level1Label: "State", level2Label: "School district", registrationLabel1: "State registration number", registrationLabel2: "NCES school ID", divisions: ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"] },
  Canada: { level1Label: "Province / Territory", level2Label: "School division", registrationLabel1: "Corporate registration number", registrationLabel2: "Ministry of Education number", divisions: ["Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Northwest Territories", "Nova Scotia", "Nunavut", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Yukon"] },
  Australia: { level1Label: "State / Territory", level2Label: "Local government area", registrationLabel1: "ABN", registrationLabel2: "State registration authority number", divisions: ["Australian Capital Territory", "New South Wales", "Northern Territory", "Queensland", "South Australia", "Tasmania", "Victoria", "Western Australia"] },
  "New Zealand": { level1Label: "Region", level2Label: "District", registrationLabel1: "NZBN", registrationLabel2: "MoE school number", divisions: ["Auckland", "Bay of Plenty", "Canterbury", "Gisborne", "Hawke’s Bay", "Manawatū-Whanganui", "Marlborough", "Nelson", "Northland", "Otago", "Southland", "Taranaki", "Tasman", "Waikato", "Wellington", "West Coast"] },
  Brazil: { level1Label: "State", level2Label: "Municipality", registrationLabel1: "CNPJ", registrationLabel2: "MEC / INEP code", divisions: ["Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins"] },
  Mexico: { level1Label: "State", level2Label: "Municipality", registrationLabel1: "RFC", registrationLabel2: "SEP CCT key", divisions: ["Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Coahuila", "Colima", "Durango", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Mexico City", "México", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas"] },
  Jamaica: { level1Label: "Parish", level2Label: "District", registrationLabel1: "Company registration number", registrationLabel2: "MoEY school code", divisions: ["Clarendon", "Hanover", "Kingston", "Manchester", "Portland", "Saint Andrew", "Saint Ann", "Saint Catherine", "Saint Elizabeth", "Saint James", "Saint Mary", "Saint Thomas", "Trelawny", "Westmoreland"] },
  "Trinidad and Tobago": { level1Label: "Region", level2Label: "Municipality", registrationLabel1: "Company registration number", registrationLabel2: "MoE school code", divisions: ["Arima", "Chaguanas", "Couva-Tabaquite-Talparo", "Diego Martin", "Mayaro-Rio Claro", "Penal-Debe", "Point Fortin", "Port of Spain", "Princes Town", "San Fernando", "San Juan-Laventille", "Sangre Grande", "Siparia", "Tobago", "Tunapuna-Piarco"] },
  France: { level1Label: "Region", level2Label: "Department", registrationLabel1: "SIRET", registrationLabel2: "Rectorat authorisation number", divisions: ["Auvergne-Rhône-Alpes", "Bourgogne-Franche-Comté", "Bretagne", "Centre-Val de Loire", "Corse", "Grand Est", "Hauts-de-France", "Île-de-France", "Normandie", "Nouvelle-Aquitaine", "Occitanie", "Pays de la Loire", "Provence-Alpes-Côte d’Azur"] },
  Germany: { level1Label: "State", level2Label: "District", registrationLabel1: "Handelsregister number", registrationLabel2: "Schulaufsicht approval number", divisions: ["Baden-Württemberg", "Bavaria", "Berlin", "Brandenburg", "Bremen", "Hamburg", "Hesse", "Lower Saxony", "Mecklenburg-Vorpommern", "North Rhine-Westphalia", "Rhineland-Palatinate", "Saarland", "Saxony", "Saxony-Anhalt", "Schleswig-Holstein", "Thuringia"] },
  Spain: { level1Label: "Autonomous community", level2Label: "Province", registrationLabel1: "CIF", registrationLabel2: "Código de centro", divisions: ["Andalusia", "Aragon", "Asturias", "Balearic Islands", "Basque Country", "Canary Islands", "Cantabria", "Castile and León", "Castilla-La Mancha", "Catalonia", "Extremadura", "Galicia", "La Rioja", "Madrid", "Murcia", "Navarre", "Valencia"] },
  Netherlands: { level1Label: "Province", level2Label: "Municipality", registrationLabel1: "KvK number", registrationLabel2: "BRIN number", divisions: ["Drenthe", "Flevoland", "Friesland", "Gelderland", "Groningen", "Limburg", "North Brabant", "North Holland", "Overijssel", "South Holland", "Utrecht", "Zeeland"] },
  Turkey: { level1Label: "Province", level2Label: "District", registrationLabel1: "Trade registry number", registrationLabel2: "MEB institution code", divisions: ["Adana", "Ankara", "Antalya", "Bursa", "Diyarbakır", "Erzurum", "Eskişehir", "Gaziantep", "Hatay", "İstanbul", "İzmir", "Kayseri", "Kocaeli", "Konya", "Malatya", "Manisa", "Mersin", "Muğla", "Samsun", "Şanlıurfa", "Trabzon", "Van"] },
  [OTHER_COUNTRY]: { level1Label: "State / Province", level2Label: "District", registrationLabel1: "Company registration number", registrationLabel2: "Education authority approval number", divisions: [] }
};

export const COUNTRY_NAMES = Object.keys(COUNTRY_GEO);

export function geoFor(country: string): CountryGeo {
  return COUNTRY_GEO[country] ?? COUNTRY_GEO[OTHER_COUNTRY];
}

/** Country-specific phone placeholder shown while the field is empty — a hint only,
    not a validation pattern (only Nigeria's format is actually checked, server-side). */
export const PHONE_PLACEHOLDER: Record<string, string> = {
  Nigeria: "+234 803 220 1190",
  Ghana: "+233 24 123 4567",
  Kenya: "+254 712 345 678",
  "South Africa": "+27 82 123 4567",
  India: "+91 98765 43210",
  "United Kingdom": "+44 7700 900123",
  "United States": "+1 202 555 0143",
  "United Arab Emirates": "+971 50 123 4567"
};
