-- Add normalized school staff roles while preserving the MVP's existing role names.
-- Existing values such as ACCOUNTANT, EXAM_OFFICER, GUIDANCE_COUNSELLOR,
-- ICT_CBT_ADMIN, NURSE, TRANSPORT_MANAGER, and HOSTEL_MISTRESS remain valid.
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'EXAMINATION_OFFICER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'BURSAR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ACCOUNT_OFFICER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'HR_OFFICER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SECURITY_OFFICER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MAINTENANCE_OFFICER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'GUIDANCE_COUNSELOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'LABORATORY_ASSISTANT';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'IT_ADMINISTRATOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SCHOOL_NURSE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TRANSPORT_COORDINATOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'HOSTEL_MATRON';
