import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

import { AdmissionApplicationView } from "@/lib/domain/types";
import { formatDate } from "@/lib/utils/formatters";

export async function buildAdmissionOfferPdf(input: {
  schoolName: string;
  application: AdmissionApplicationView;
}) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold);

  page.drawRectangle({ x: 0, y: 780, width: 595, height: 62, color: rgb(0.14, 0.35, 0.25) });
  page.drawText(input.schoolName, { x: 40, y: 810, size: 22, font: boldFont, color: rgb(1, 1, 1) });
  page.drawText("Admission Offer Letter", { x: 40, y: 792, size: 11, font, color: rgb(0.92, 0.94, 0.93) });

  const lines = [
    `Application No: ${input.application.applicationNo}`,
    `Applicant: ${input.application.studentName}`,
    `Class Offered: ${input.application.desiredClass}`,
    `Guardian: ${input.application.guardianName}`,
    `Status: ${input.application.status}`,
    input.application.offerExpiresAt ? `Offer Expires: ${formatDate(input.application.offerExpiresAt)}` : ""
  ].filter(Boolean);

  page.drawText("Dear Parent/Guardian,", { x: 40, y: 730, size: 12, font: boldFont, color: rgb(0.1, 0.13, 0.12) });
  page.drawText(
    "We are pleased to communicate the admission decision for the applicant listed below. Please follow the acceptance, payment clearance, and onboarding instructions provided by the school.",
    { x: 40, y: 700, size: 11, font, color: rgb(0.1, 0.13, 0.12), maxWidth: 510, lineHeight: 16 }
  );

  lines.forEach((line, index) => {
    page.drawText(line, { x: 40, y: 635 - index * 24, size: 12, font, color: rgb(0.1, 0.13, 0.12) });
  });

  page.drawText("Next steps", { x: 40, y: 455, size: 14, font: boldFont, color: rgb(0.1, 0.13, 0.12) });
  [
    "1. Accept the offer before the expiry date.",
    "2. Complete required financial clearance with the bursary office.",
    "3. Submit any outstanding documents requested by admissions.",
    "4. Report to the admin office for class allocation and portal onboarding."
  ].forEach((line, index) => {
    page.drawText(line, { x: 40, y: 430 - index * 22, size: 11, font, color: rgb(0.1, 0.13, 0.12) });
  });

  page.drawText("Generated by FutureRealm SMS", {
    x: 40,
    y: 80,
    size: 10,
    font,
    color: rgb(0.4, 0.45, 0.42)
  });

  return pdf.save();
}
