import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

import { GradeRecordView, StudentRecordView } from "@/lib/domain/types";

export async function buildReportCardPdf(input: {
  schoolName: string;
  student: StudentRecordView;
  sessionLabel: string;
  termLabel: string;
  grades: GradeRecordView[];
}) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold);

  page.drawRectangle({
    x: 0,
    y: 780,
    width: 595,
    height: 62,
    color: rgb(0.14, 0.35, 0.25)
  });

  page.drawText(input.schoolName, {
    x: 40,
    y: 810,
    size: 24,
    font: boldFont,
    color: rgb(1, 1, 1)
  });
  page.drawText(`${input.sessionLabel} · ${input.termLabel} Report Card`, {
    x: 40,
    y: 792,
    size: 11,
    font,
    color: rgb(0.92, 0.94, 0.93)
  });

  const details = [
    `Student: ${input.student.fullName}`,
    `Admission No: ${input.student.admissionNumber}`,
    `Class: ${input.student.className}`,
    `Attendance: ${input.student.attendanceRate.toFixed(1)}%`,
    `Average: ${input.student.averageScore.toFixed(1)}%`
  ];

  details.forEach((detail, index) => {
    page.drawText(detail, {
      x: 40,
      y: 745 - index * 18,
      size: 12,
      font,
      color: rgb(0.1, 0.13, 0.12)
    });
  });

  page.drawText("Subjects", {
    x: 40,
    y: 635,
    size: 13,
    font: boldFont,
    color: rgb(0.1, 0.13, 0.12)
  });
  page.drawText("CA", { x: 300, y: 635, size: 13, font: boldFont, color: rgb(0.1, 0.13, 0.12) });
  page.drawText("Exam", { x: 355, y: 635, size: 13, font: boldFont, color: rgb(0.1, 0.13, 0.12) });
  page.drawText("Total", { x: 420, y: 635, size: 13, font: boldFont, color: rgb(0.1, 0.13, 0.12) });
  page.drawText("Grade", { x: 485, y: 635, size: 13, font: boldFont, color: rgb(0.1, 0.13, 0.12) });

  input.grades.forEach((grade, index) => {
    const y = 605 - index * 24;
    page.drawText(grade.subject, {
      x: 40,
      y,
      size: 12,
      font,
      color: rgb(0.1, 0.13, 0.12)
    });
    page.drawText(`${grade.continuousAssessment}`, { x: 305, y, size: 12, font });
    page.drawText(`${grade.exam}`, { x: 360, y, size: 12, font });
    page.drawText(`${grade.total}`, { x: 425, y, size: 12, font });
    page.drawText(grade.grade, { x: 490, y, size: 12, font: boldFont });
  });

  page.drawText("Generated by FutureRealm SMS", {
    x: 40,
    y: 80,
    size: 10,
    font,
    color: rgb(0.4, 0.45, 0.42)
  });

  return pdf.save();
}
