UPDATE "PlatformSubscriptionPlan"
SET "isActive" = false
WHERE "slug" IN ('basic', 'professional', 'enterprise');

INSERT INTO "PlatformSubscriptionPlan" (
  "id",
  "name",
  "slug",
  "plan",
  "monthlyPrice",
  "annualPrice",
  "studentLimit",
  "staffLimit",
  "storageLimitGb",
  "smsUnitsPerMonth",
  "emailSendsPerMonth",
  "supportTier",
  "apiAccess",
  "customBranding",
  "includedModules",
  "isActive",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    'plan_starter_semester',
    'Starter',
    'starter',
    'BASIC',
    1500,
    3000,
    250,
    NULL,
    25,
    0,
    5000,
    'EMAIL',
    false,
    false,
    '{"modules":["Core modules","Email notifications"],"features":["1-250 students","Email notifications","All core modules"]}'::jsonb,
    true,
    NOW(),
    NOW()
  ),
  (
    'plan_standard_semester',
    'Standard',
    'standard',
    'STANDARD',
    3500,
    7000,
    700,
    NULL,
    150,
    10000,
    35000,
    'PRIORITY',
    false,
    false,
    '{"modules":["Core modules","SMS notifications","WhatsApp notifications","Payment integration"],"features":["251-700 students","SMS and WhatsApp notifications","Payment integration"]}'::jsonb,
    true,
    NOW(),
    NOW()
  ),
  (
    'plan_elite_semester',
    'Elite',
    'elite',
    'ENTERPRISE',
    5500,
    11000,
    NULL,
    NULL,
    300,
    25000,
    70000,
    'DEDICATED',
    true,
    true,
    '{"modules":["All core modules","Predictive analytics","Custom branding","Account manager"],"features":["701+ students","Predictive analytics","Custom branding","Dedicated account manager"]}'::jsonb,
    true,
    NOW(),
    NOW()
  ),
  (
    'plan_ngo_mission_semester',
    'NGO / Mission',
    'ngo-mission',
    'CUSTOM',
    150,
    300,
    NULL,
    NULL,
    25,
    0,
    5000,
    'EMAIL',
    false,
    false,
    '{"modules":["Core modules","Annual verification"],"features":["Any size","90% off selected tier","CAC or charity certificate required","Verified annually"]}'::jsonb,
    true,
    NOW(),
    NOW()
  ),
  (
    'plan_trial_semester',
    'Trial',
    'trial',
    'PROFESSIONAL',
    0,
    0,
    NULL,
    NULL,
    25,
    0,
    5000,
    'EMAIL',
    false,
    false,
    '{"modules":["Starter features"],"features":["Any size","One full term","All Starter features","Free"]}'::jsonb,
    true,
    NOW(),
    NOW()
  )
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "plan" = EXCLUDED."plan",
  "monthlyPrice" = EXCLUDED."monthlyPrice",
  "annualPrice" = EXCLUDED."annualPrice",
  "studentLimit" = EXCLUDED."studentLimit",
  "staffLimit" = EXCLUDED."staffLimit",
  "storageLimitGb" = EXCLUDED."storageLimitGb",
  "smsUnitsPerMonth" = EXCLUDED."smsUnitsPerMonth",
  "emailSendsPerMonth" = EXCLUDED."emailSendsPerMonth",
  "supportTier" = EXCLUDED."supportTier",
  "apiAccess" = EXCLUDED."apiAccess",
  "customBranding" = EXCLUDED."customBranding",
  "includedModules" = EXCLUDED."includedModules",
  "isActive" = true,
  "updatedAt" = NOW();
