import type { Route } from "next";
import Link from "next/link";

import { TableCard } from "@/components/data-display/table-card";
import { StatusBadge } from "@/components/data-display/status-badge";
import { AccessDenied } from "@/components/feedback/access-denied";
import { PrincipalMetricCard, PrincipalPageHeader, PrincipalQuickLink } from "@/components/portals/principal-portal-ui";
import { getDefaultPathForRole } from "@/lib/auth/roles";
import { canAccessServerPath } from "@/lib/auth/server-access";
import { getServerSession } from "@/lib/auth/session";
import { loadPrincipalDashboardBundle } from "@/lib/principal/portal";
import { formatDate } from "@/lib/utils/formatters";

export default async function PrincipalApprovalsPage() {
  const session = await getServerSession();
  if (!session) return null;

  if (!(await canAccessServerPath(session, "/portals/principal/approvals"))) {
    return <AccessDenied backHref={getDefaultPathForRole(session.role)} />;
  }

  const { overview, approvalQueue, admissions } = await loadPrincipalDashboardBundle();
  const resultPending = approvalQueue.length;
  const actionPending = overview.pendingActions?.length ?? 0;
  const admissionPending = admissions?.pendingApprovals ?? 0;

  return (
    <div className="grid gap-6">
      <PrincipalPageHeader
        eyebrow="Approvals desk"
        title="Decision queue for principal sign-off"
        description="Keep publication, admissions, and operational escalations moving with a single approval workspace built around urgency."
        actions={<PrincipalQuickLink href="/portals/principal" label="Back to dashboard" />}
      />

      <section className="grid gap-4 md:grid-cols-3">
        <PrincipalMetricCard label="Academic Queue" value={resultPending} helper="Result-sheet approvals currently waiting for action." />
        <PrincipalMetricCard label="Leadership Actions" value={actionPending} helper="Priority tasks routed into the principal command queue." tone="amber" />
        <PrincipalMetricCard label="Admission Decisions" value={admissionPending} helper="Applications still requiring principal decision or escalation." tone="rose" />
      </section>

      <TableCard
        title="Academic approval queue"
        description="Result approvals generated by the current broadsheet and score workflow."
        items={approvalQueue}
        emptyState="No academic approvals are waiting on this account."
        primaryColumnKey="student"
        featuredColumnKeys={["status"]}
        getRowKey={(item) => item.id}
        columns={[
          {
            key: "student",
            header: "Student / Class",
            render: (item) => (
              <div>
                <p className="font-semibold text-[var(--color-text-primary)]">{item.studentName}</p>
                <p className="text-xs text-[var(--color-text-secondary)]">{item.className}</p>
              </div>
            ),
          },
          { key: "action", header: "Action", render: (item) => item.action },
          { key: "status", header: "Status", render: (item) => <StatusBadge status={item.status} /> },
          { key: "actor", header: "Requested by", render: (item) => item.actorName },
          { key: "date", header: "Created", render: (item) => formatDate(item.createdAt) },
        ]}
      />

      <TableCard
        title="Leadership action queue"
        description="Cross-functional alerts already surfaced in the school-wide dashboard overview."
        items={overview.pendingActions ?? []}
        emptyState="Nothing is waiting in the leadership queue right now."
        primaryColumnKey="title"
        featuredColumnKeys={["tone"]}
        getRowKey={(item) => item.id}
        columns={[
          {
            key: "title",
            header: "Request",
            render: (item) => (
              <div>
                <p className="font-semibold text-[var(--color-text-primary)]">{item.title}</p>
                <p className="text-xs text-[var(--color-text-secondary)]">{item.detail}</p>
              </div>
            ),
          },
          { key: "tone", header: "Urgency", render: (item) => <StatusBadge status={item.tone.toUpperCase()} /> },
          {
            key: "workspace",
            header: "Workspace",
            render: (item) => (
              <Link href={item.href as Route} className="font-semibold text-[var(--color-text-accent)]">
                Open task
              </Link>
            ),
          },
        ]}
      />
    </div>
  );
}
