/**
 * The school's approval routes, verbatim from the mockup.
 *
 * A route decides who may decide. Nobody can approve their own submission,
 * whatever any route says — that rule sits above routing and cannot be
 * switched off.
 */
export type ApprovalRoute = {
  name: string;
  module: string;
  approver: string;
  /** Empty when a single approver is enough. */
  second: string;
  escalates: string;
  /** Items currently sitting on this route. */
  open: number;
  source: "Default" | "School override";
  /** Why the route exists at all — shown under its name. */
  why: string;
  /** Some decisions can never be bulk-approved, whatever a route says. */
  noBulk?: boolean;
  average: string;
  /** What waits while this route is undecided. */
  blocks: string;
};

export const approvalRoutes: ApprovalRoute[] = [
  {
    name: "Score correction",
    module: "Scores & Results",
    approver: "Exam Officer",
    second: "",
    escalates: "5 days",
    open: 9,
    source: "School override",
    why: "Blocks report cards",
    noBulk: true,
    average: "2.1 days",
    blocks: "34 report cards",
  },
  {
    name: "Score sheet approval",
    module: "Scores & Results",
    approver: "Exam Officer",
    second: "",
    escalates: "3 days",
    open: 6,
    source: "Default",
    why: "The last check before a mark is final",
    average: "1.6 days",
    blocks: "Every card in the arm",
  },
  {
    name: "Results publication",
    module: "Report Cards",
    approver: "Principal",
    second: "Proprietor",
    escalates: "3 days",
    open: 1,
    source: "Default",
    why: "Irreversible once published",
    average: "2.8 days",
    blocks: "112 report cards",
  },
  {
    name: "Report card revision",
    module: "Report Cards",
    approver: "Principal",
    second: "",
    escalates: "2 days",
    open: 0,
    source: "Default",
    why: "A family has already seen the first version",
    noBulk: true,
    average: "1.1 days",
    blocks: "One family at a time",
  },
  {
    name: "Fee waiver above ₦50,000",
    module: "Fee Management",
    approver: "Principal",
    second: "Proprietor",
    escalates: "7 days",
    open: 4,
    source: "Default",
    why: "Money leaving the ledger",
    average: "8.6 days",
    blocks: "A family in difficulty",
  },
  {
    name: "Fee waiver up to ₦50,000",
    module: "Fee Management",
    approver: "Bursar",
    second: "",
    escalates: "5 days",
    open: 2,
    source: "School override",
    why: "Delegated to the Bursar",
    average: "1.4 days",
    blocks: "A family in difficulty",
  },
  {
    name: "Payment reversal",
    module: "Fee Management",
    approver: "Bursar",
    second: "Proprietor",
    escalates: "3 days",
    open: 3,
    source: "Default",
    why: "Money leaving a ledger",
    noBulk: true,
    average: "5.2 days",
    blocks: "The family’s balance",
  },
  {
    name: "Fee structure publication",
    module: "Fee Management",
    approver: "Proprietor",
    second: "",
    escalates: "5 days",
    open: 0,
    source: "Default",
    why: "Generates every invoice in the school",
    average: "3.0 days",
    blocks: "Invoicing for the term",
  },
  {
    name: "Student status change",
    module: "Student Records",
    approver: "Principal",
    second: "",
    escalates: "5 days",
    open: 1,
    source: "Default",
    why: "Withdrawal, transfer or alumni",
    noBulk: true,
    average: "1.9 days",
    blocks: "The child’s enrolment",
  },
  {
    name: "Record change · date of birth",
    module: "Student Records",
    approver: "Principal",
    second: "",
    escalates: "5 days",
    open: 1,
    source: "Default",
    why: "Evidence required",
    average: "1.2 days",
    blocks: "Examination registration",
  },
  {
    name: "Admission offer",
    module: "Student Records",
    approver: "Principal",
    second: "",
    escalates: "3 days",
    open: 0,
    source: "Default",
    why: "A commitment to a family",
    average: "1.7 days",
    blocks: "The applicant",
  },
  {
    name: "Backdated attendance",
    module: "Attendance",
    approver: "Principal",
    second: "",
    escalates: "2 days",
    open: 1,
    source: "School override",
    why: "Permission-gated as well as routed",
    average: "0.9 days",
    blocks: "The term percentage",
  },
  {
    name: "Register correction",
    module: "Attendance",
    approver: "Principal",
    second: "",
    escalates: "2 days",
    open: 0,
    source: "Default",
    why: "Changes a child’s attendance figure",
    average: "0.7 days",
    blocks: "One register",
  },
  {
    name: "New staff account",
    module: "Staff & Access",
    approver: "Principal",
    second: "",
    escalates: "3 days",
    open: 1,
    source: "Default",
    why: "Creates access to children’s records",
    average: "0.9 days",
    blocks: "The new joiner",
  },
  {
    name: "Access above the role template",
    module: "Staff & Access",
    approver: "Proprietor",
    second: "",
    escalates: "3 days",
    open: 0,
    source: "Default",
    why: "More reach than the role intends",
    noBulk: true,
    average: "1.4 days",
    blocks: "The staff member",
  },
  {
    name: "Sensitive group grant",
    module: "Staff & Access",
    approver: "Proprietor",
    second: "",
    escalates: "2 days",
    open: 0,
    source: "Default",
    why: "Health, counselling and safeguarding records",
    noBulk: true,
    average: "1.0 days",
    blocks: "The staff member",
  },
  {
    name: "Mass communication above threshold",
    module: "Communication",
    approver: "Principal",
    second: "",
    escalates: "1 day",
    open: 1,
    source: "Default",
    why: "Above 150 recipients",
    average: "0.3 days",
    blocks: "The send",
  },
  {
    name: "Timetable publication",
    module: "Classes & Timetable",
    approver: "Principal",
    second: "",
    escalates: "3 days",
    open: 1,
    source: "Default",
    why: "Changes where every teacher stands",
    average: "1.5 days",
    blocks: "The new week",
  },
];
