import type { Role } from "@/lib/domain/types";
import { systemRolePermissionKeys } from "@/lib/permissions/catalog";

export type PortalType = "school" | "super_admin";

export type NavigationGroup =
  | "Overview"
  | "Attendance"
  | "Approvals"
  | "Academic Operations"
  | "My Classes"
  | "My Class"
  | "Patients"
  | "Emergencies"
  | "Medical Supplies"
  | "Screenings"
  | "Circulation"
  | "Catalog"
  | "Members"
  | "Programs"
  | "Visitors"
  | "Students"
  | "Parcels & Mail"
  | "Lost & Found"
  | "Meeting Rooms"
  | "Calls & Messages"
  | "Boarders"
  | "Exeat"
  | "Incidents"
  | "Maintenance"
  | "Schedules"
  | "Fleet"
  | "Routes"
  | "Drivers"
  | "Alerts"
  | "People"
  | "Finance"
  | "Operations"
  | "School Growth"
  | "Welfare"
  | "Communication"
  | "Content"
  | "HR"
  | "Management"
  | "Reports"
  | "Account"
  | "Student Portal"
  | "Parent Portal"
  | "Teacher Portal"
  | "Admissions Portal"
  | "Exam Portal"
  | "Platform";

export type NavigationRegistryItem = {
  id: string;
  label: string;
  icon: string;
  path: string;
  requiredPermissions: string[];
  portalType: PortalType;
  group: NavigationGroup | null;
  requireAny?: boolean;
  hideFromSidebar?: boolean;
  badge?: string;
  order: number;
};

export type NavigationGroupView = {
  title: string;
  items: NavigationRegistryItem[];
};

const platformPermissionByRole: Record<Role, string[]> = {
  PLATFORM_OWNER: ["sa.*"],
  SUPER_ADMIN: ["sa.*"],
  PLATFORM_ADMIN: [
    "sa.dashboard.view",
    "sa.schools.view",
    "sa.schools.create",
    "sa.schools.edit",
    "sa.users.view",
    "sa.users.reset_password",
    "sa.billing.view",
    "sa.analytics.view",
    "sa.support.view",
    "sa.support.manage",
    "sa.communications.view",
    "sa.communications.create",
    "sa.feature_flags.view",
    "sa.feature_flags.manage",
    "sa.security.view",
    "sa.crm.view",
    "sa.crm.manage",
    "sa.settings.view",
    "sa.settings.edit",
    "sa.audit_logs.view",
  ],
  SUPPORT_AGENT: [
    "sa.dashboard.view",
    "sa.schools.view",
    "sa.users.view",
    "sa.users.reset_password",
    "sa.support.view",
    "sa.support.manage",
    "sa.security.view",
    "sa.crm.view",
    "sa.audit_logs.view",
  ],
  SALES_MANAGER: [
    "sa.dashboard.view",
    "sa.schools.view",
    "sa.schools.create",
    "sa.schools.edit",
    "sa.billing.view",
    "sa.billing.edit_plan",
    "sa.analytics.view",
    "sa.communications.view",
    "sa.communications.create",
    "sa.crm.view",
    "sa.crm.manage",
  ],
  FINANCE_MANAGER: [
    "sa.dashboard.view",
    "sa.billing.view",
    "sa.billing.manage",
    "sa.analytics.view",
    "sa.revenue_reports.view",
  ],
  DEVELOPER: [
    "sa.dashboard.view",
    "sa.schools.view",
    "sa.support.view",
    "sa.communications.view",
    "sa.feature_flags.view",
    "sa.feature_flags.manage",
    "sa.security.view",
    "sa.settings.view",
    "sa.audit_logs.view",
  ],
  SCHOOL_OWNER: [],
  PROPRIETOR: [],
  ADMINISTRATOR: [],
  PRINCIPAL: [],
  HEAD_TEACHER: [],
  VICE_PRINCIPAL_ACADEMICS: [],
  VICE_PRINCIPAL_ADMINISTRATION: [],
  VICE_PRINCIPAL_SPECIAL_DUTIES: [],
  ADMIN_OFFICER: [],
  TEACHER: [],
  EXAM_OFFICER: [],
  EXAMINATION_OFFICER: [],
  HEAD_OF_DEPARTMENT: [],
  CLASS_TEACHER: [],
  SUBJECT_TEACHER: [],
  BURSAR: [],
  ACCOUNTANT: [],
  ACCOUNT_OFFICER: [],
  HR_OFFICER: [],
  SECURITY_OFFICER: [],
  MAINTENANCE_OFFICER: [],
  PARENT: [],
  STUDENT: [],
  ADMISSIONS_OFFICER: [],
  GUIDANCE_COUNSELOR: [],
  GUIDANCE_COUNSELLOR: [],
  LIBRARIAN: [],
  LABORATORY_STAFF: [],
  LABORATORY_ASSISTANT: [],
  ICT_CBT_ADMIN: [],
  IT_ADMINISTRATOR: [],
  ATTENDANCE_OFFICER: [],
  SCHOOL_NURSE: [],
  NURSE: [],
  RECEPTIONIST: [],
  TRANSPORT_COORDINATOR: [],
  TRANSPORT_MANAGER: [],
  HOSTEL_MANAGER: [],
  HOSTEL_MASTER: [],
  HOSTEL_MATRON: [],
  HOSTEL_MISTRESS: [],
  STORE_OFFICER: [],
};

export const NAV_REGISTRY: NavigationRegistryItem[] = [
  {
    id: "sa_dashboard",
    label: "Command Center",
    icon: "LayoutDashboard",
    path: "/super-admin",
    requiredPermissions: ["sa.dashboard.view"],
    portalType: "super_admin",
    group: "Overview",
    order: 1,
  },
  {
    id: "sa_schools",
    label: "School Accounts",
    icon: "Building2",
    path: "/super-admin/schools",
    requiredPermissions: ["sa.schools.view"],
    portalType: "super_admin",
    group: "School Growth",
    order: 2,
  },
  {
    id: "sa_billing",
    label: "Subscription & Billing",
    icon: "CreditCard",
    path: "/super-admin/billing",
    requiredPermissions: ["sa.billing.view"],
    portalType: "super_admin",
    group: "School Growth",
    order: 3,
  },
  {
    id: "sa_communications",
    label: "Notification Center",
    icon: "Megaphone",
    path: "/super-admin/communications",
    requiredPermissions: ["sa.communications.view"],
    portalType: "super_admin",
    group: "School Growth",
    order: 4,
  },
  {
    id: "sa_crm",
    label: "CRM & Sales",
    icon: "Target",
    path: "/super-admin/crm",
    requiredPermissions: ["sa.crm.view"],
    portalType: "super_admin",
    group: "School Growth",
    order: 5,
  },
  {
    id: "sa_users",
    label: "User Management",
    icon: "Users",
    path: "/super-admin/users",
    requiredPermissions: ["sa.users.view"],
    portalType: "super_admin",
    group: "Operations",
    order: 6,
  },
  {
    id: "sa_support",
    label: "Support & Ticketing",
    icon: "Headphones",
    path: "/super-admin/support",
    requiredPermissions: ["sa.support.view"],
    portalType: "super_admin",
    group: "Operations",
    badge: "openTicketsCount",
    order: 7,
  },
  {
    id: "sa_analytics",
    label: "Analytics & BI",
    icon: "BarChart3",
    path: "/super-admin/analytics",
    requiredPermissions: ["sa.analytics.view"],
    portalType: "super_admin",
    group: "Operations",
    order: 8,
  },
  {
    id: "sa_feature_flags",
    label: "Feature & Tier Config",
    icon: "Flag",
    path: "/super-admin/feature-flags",
    requiredPermissions: ["sa.feature_flags.view"],
    portalType: "super_admin",
    group: "Platform",
    order: 9,
  },
  {
    id: "sa_security",
    label: "Security & Audit",
    icon: "ShieldCheck",
    path: "/super-admin/security",
    requiredPermissions: ["sa.security.view"],
    portalType: "super_admin",
    group: "Platform",
    order: 10,
  },
  {
    id: "sa_audit_logs",
    label: "Audit Logs",
    icon: "FileClock",
    path: "/super-admin/audit-logs",
    requiredPermissions: ["sa.audit_logs.view"],
    portalType: "super_admin",
    group: "Platform",
    order: 11,
  },
  {
    id: "sa_system_health",
    label: "Infrastructure",
    icon: "Activity",
    path: "/super-admin/system",
    requiredPermissions: ["sa.security.view"],
    portalType: "super_admin",
    group: "Platform",
    order: 12,
  },
  {
    id: "sa_config_library",
    label: "Curriculum Library",
    icon: "BookMarked",
    path: "/super-admin/config-library",
    requiredPermissions: ["sa.settings.view"],
    portalType: "super_admin",
    group: "Platform",
    order: 13,
  },
  {
    id: "sa_internal_team",
    label: "Team & Roles",
    icon: "UserCog",
    path: "/super-admin/internal-team",
    requiredPermissions: ["sa.settings.view"],
    portalType: "super_admin",
    group: "Platform",
    order: 14,
  },
  {
    id: "sa_settings",
    label: "Settings",
    icon: "Settings2",
    path: "/super-admin/settings",
    requiredPermissions: ["sa.settings.view"],
    portalType: "super_admin",
    group: "Platform",
    order: 15,
  },

  {
    id: "dashboard",
    label: "Command Center",
    icon: "LayoutDashboard",
    path: "/dashboard",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    order: 1,
  },
  {
    id: "students",
    label: "Student Records",
    icon: "GraduationCap",
    path: "/students",
    requiredPermissions: ["students.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 10,
  },
  {
    id: "classes",
    label: "Classes",
    icon: "BookOpen",
    path: "/classes",
    requiredPermissions: ["classes.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 10.5,
  },
  {
    id: "timetable",
    label: "Timetable",
    icon: "Calendar",
    path: "/timetable",
    requiredPermissions: ["timetable.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 10.8,
  },
  {
    id: "attendance",
    label: "Attendance",
    icon: "ClipboardCheck",
    path: "/attendance",
    requiredPermissions: ["attendance.view", "attendance.mark"],
    requireAny: true,
    portalType: "school",
    group: "Academic Operations",
    hideFromSidebar: true,
    order: 11,
  },
  {
    id: "curriculum",
    label: "Scheme of Work",
    icon: "BookOpen",
    path: "/academics/curriculum",
    requiredPermissions: ["subjects.view", "lesson_plans.view"],
    requireAny: true,
    portalType: "school",
    group: "Academic Operations",
    hideFromSidebar: true,
    order: 12,
  },
  {
    id: "subjects",
    label: "Subjects",
    icon: "BookMarked",
    path: "/subjects",
    requiredPermissions: ["subjects.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 13,
  },
  {
    id: "subjects_legacy",
    label: "Subjects",
    icon: "BookMarked",
    path: "/academics/subjects",
    requiredPermissions: ["subjects.view"],
    portalType: "school",
    group: "Academic Operations",
    hideFromSidebar: true,
    order: 13.1,
  },
  {
    id: "assessment_format",
    label: "Assessment Format",
    icon: "FileCheck",
    path: "/academics/results/assessment-format",
    requiredPermissions: ["settings.grading", "results.compile", "results.approve", "exams.view"],
    requireAny: true,
    portalType: "school",
    group: "Academic Operations",
    order: 14,
  },
  {
    id: "results",
    label: "Results & Broadsheets",
    icon: "Award",
    path: "/academics/results",
    requiredPermissions: ["results.view"],
    portalType: "school",
    group: "Academic Operations",
    hideFromSidebar: true,
    order: 15,
  },
  {
    id: "result_settings",
    label: "Assessment Format",
    icon: "Settings2",
    path: "/academics/results/settings",
    requiredPermissions: ["settings.grading", "results.compile", "results.approve", "exams.view"],
    requireAny: true,
    portalType: "school",
    group: "Academic Operations",
    hideFromSidebar: true,
    order: 15.1,
  },
  {
    id: "result_approvals",
    label: "Result Approvals",
    icon: "ClipboardCheck",
    path: "/academics/results/approvals",
    requiredPermissions: ["results.approve"],
    portalType: "school",
    group: "Academic Operations",
    hideFromSidebar: true,
    order: 15.2,
  },
  {
    id: "result_publish",
    label: "Publish Results",
    icon: "FileCheck",
    path: "/academics/results/publish",
    requiredPermissions: ["results.publish"],
    portalType: "school",
    group: "Academic Operations",
    hideFromSidebar: true,
    order: 15.3,
  },
  {
    id: "result_analytics",
    label: "Result Analytics",
    icon: "BarChart3",
    path: "/academics/results/analytics",
    requiredPermissions: ["reports.view"],
    portalType: "school",
    group: "Academic Operations",
    hideFromSidebar: true,
    order: 15.4,
  },
  {
    id: "result_history",
    label: "Result History",
    icon: "FileClock",
    path: "/academics/results/history",
    requiredPermissions: ["results.view"],
    portalType: "school",
    group: "Academic Operations",
    hideFromSidebar: true,
    order: 15.5,
  },
  {
    id: "result_report_cards",
    label: "Report Cards",
    icon: "FileText",
    path: "/academics/results/report-cards",
    requiredPermissions: ["results.export"],
    portalType: "school",
    group: "Academic Operations",
    hideFromSidebar: true,
    order: 15.6,
  },
  {
    id: "result_broadsheets",
    label: "Broadsheet",
    icon: "Award",
    path: "/academics/results/broadsheets",
    requiredPermissions: ["results.view"],
    portalType: "school",
    group: "Academic Operations",
    hideFromSidebar: false,
    order: 15.7,
  },
  {
    id: "assessment_format_legacy",
    label: "Assessment Format",
    icon: "FileCheck",
    path: "/academics/results/assessments",
    requiredPermissions: ["settings.grading", "results.compile", "results.approve", "exams.view"],
    requireAny: true,
    portalType: "school",
    group: "Academic Operations",
    hideFromSidebar: true,
    order: 15.8,
  },
  {
    id: "staff",
    label: "Staff & Access",
    icon: "UserRoundCog",
    path: "/school/staff",
    requiredPermissions: ["staff.view"],
    portalType: "school",
    group: "People",
    order: 19,
  },
  {
    id: "teachers",
    label: "Teachers",
    icon: "Users",
    path: "/teachers",
    requiredPermissions: ["teachers.view", "staff.view"],
    requireAny: true,
    portalType: "school",
    group: "People",
    hideFromSidebar: true,
    order: 20,
  },
  {
    id: "parents",
    label: "Parent & Guardians",
    icon: "Users",
    path: "/parents",
    requiredPermissions: ["parents.view"],
    portalType: "school",
    group: "People",
    order: 20.2,
  },
  {
    id: "profiles",
    label: "Profiles",
    icon: "UserCircle",
    path: "/school/profile",
    requiredPermissions: ["profiles.view"],
    portalType: "school",
    group: "People",
    hideFromSidebar: true,
    order: 20.4,
  },
  {
    id: "staff_attendance_admin",
    label: "Staff Attendance",
    icon: "UserCheck",
    path: "/teachers/attendance",
    requiredPermissions: ["staff_attendance.view"],
    portalType: "school",
    group: "HR",
    order: 21,
  },
  {
    id: "staff_leave",
    label: "Staff Leave",
    icon: "ClipboardList",
    path: "/school/staff",
    requiredPermissions: ["staff_leave.view"],
    portalType: "school",
    group: "HR",
    order: 21.5,
  },
  {
    id: "teacher_training_admin",
    label: "Teacher Training",
    icon: "ClipboardList",
    path: "/teachers/training",
    requiredPermissions: ["staff.view"],
    portalType: "school",
    group: "HR",
    order: 22,
  },
  {
    id: "admissions",
    label: "Admissions",
    icon: "UserPlus",
    path: "/admissions",
    requiredPermissions: ["admissions.view"],
    portalType: "school",
    group: "People",
    order: 23,
  },
  {
    id: "finance",
    label: "Fee Management",
    icon: "CreditCard",
    path: "/finance",
    requiredPermissions: ["fees.view"],
    portalType: "school",
    group: "Finance",
    order: 30,
  },
  {
    id: "finance_fee_structures",
    label: "Fee Structures",
    icon: "WalletCards",
    path: "/finance/fee-structures",
    requiredPermissions: ["fees.view"],
    portalType: "school",
    group: "Finance",
    order: 31,
  },
  {
    id: "finance_payments",
    label: "Payments & Receipts",
    icon: "Banknote",
    path: "/finance/payments",
    requiredPermissions: ["fees.view"],
    portalType: "school",
    group: "Finance",
    order: 32,
  },
  {
    id: "finance_installments",
    label: "Discounts & Plans",
    icon: "CalendarRange",
    path: "/finance/installments",
    requiredPermissions: ["fees.view"],
    portalType: "school",
    group: "Finance",
    order: 33,
  },
  {
    id: "finance_payroll",
    label: "Staff Payroll",
    icon: "BadgeDollarSign",
    path: "/finance/payroll",
    requiredPermissions: ["salaries.view"],
    portalType: "school",
    group: "Finance",
    order: 34,
  },
  {
    id: "finance_expenditures",
    label: "Expenditure",
    icon: "ReceiptText",
    path: "/finance/expenditures",
    requiredPermissions: ["expenses.view"],
    portalType: "school",
    group: "Finance",
    order: 35,
  },
  {
    id: "finance_reports",
    label: "Finance Reports",
    icon: "BarChart3",
    path: "/finance/reports",
    requiredPermissions: ["reports.view"],
    portalType: "school",
    group: "Finance",
    order: 36,
  },
  {
    id: "finance_audit",
    label: "Audit Log",
    icon: "FileClock",
    path: "/finance/audit",
    requiredPermissions: ["audit_logs.view"],
    portalType: "school",
    group: "Finance",
    order: 37,
  },
  {
    id: "finance_settings",
    label: "Finance Settings",
    icon: "Settings2",
    path: "/finance/settings",
    requiredPermissions: ["fees.edit"],
    portalType: "school",
    group: "Finance",
    order: 38,
  },
  {
    id: "communications",
    label: "Communication Center",
    icon: "Megaphone",
    path: "/communications",
    requiredPermissions: ["announcements.view", "messaging.view"],
    requireAny: true,
    portalType: "school",
    group: "Communication",
    order: 40,
  },
  {
    id: "announcements",
    label: "Announcements",
    icon: "Megaphone",
    path: "/communications",
    requiredPermissions: ["announcements.view"],
    portalType: "school",
    group: "Communication",
    order: 41,
  },
  {
    id: "messaging",
    label: "Messaging",
    icon: "Megaphone",
    path: "/communications",
    requiredPermissions: ["messaging.view", "messaging.send"],
    requireAny: true,
    portalType: "school",
    group: "Communication",
    order: 42,
  },
  {
    id: "approvals",
    label: "Approvals & Workflow",
    icon: "ClipboardCheck",
    path: "/approvals",
    requiredPermissions: ["results.approve", "admissions.approve"],
    requireAny: true,
    portalType: "school",
    group: "Approvals",
    order: 43,
  },
  {
    id: "audit",
    label: "Audit & Security",
    icon: "ShieldCheck",
    path: "/audit",
    requiredPermissions: ["audit_logs.view", "roles.view"],
    requireAny: true,
    portalType: "school",
    group: "Approvals",
    order: 44,
  },
  {
    id: "subscription",
    label: "Subscription & Billing",
    icon: "CreditCard",
    path: "/subscription",
    requiredPermissions: ["config.school_information.view", "config.manage"],
    requireAny: true,
    portalType: "school",
    group: "Finance",
    order: 39,
  },
  {
    id: "sync",
    label: "Sync & Support",
    icon: "RefreshCcw",
    path: "/sync",
    requiredPermissions: ["config.school_information.view", "config.manage"],
    requireAny: true,
    portalType: "school",
    group: "Operations",
    order: 90,
  },
  {
    id: "analytics",
    label: "Analytics & Reports",
    icon: "BarChart3",
    path: "/analytics",
    requiredPermissions: ["reports.view", "students.view"],
    portalType: "school",
    group: "Management",
    order: 50,
  },
  {
    id: "class_reports",
    label: "Class Reports",
    icon: "FileText",
    path: "/academics/results/report-cards",
    requiredPermissions: ["class_reports.view"],
    portalType: "school",
    group: "Management",
    order: 51,
  },
  {
    id: "report_cards",
    label: "Report Cards",
    icon: "FileText",
    path: "/academics/results/report-cards",
    requiredPermissions: [
      "report_cards.view",
      "report_cards.generate",
      "report_cards.download",
    ],
    requireAny: true,
    portalType: "school",
    group: "Management",
    order: 52,
  },
  {
    id: "audit_logs",
    label: "Audit Logs",
    icon: "FileClock",
    path: "/analytics",
    requiredPermissions: ["audit_logs.view"],
    portalType: "school",
    group: "Management",
    order: 53,
  },
  {
    id: "data_export",
    label: "Data Export",
    icon: "FileText",
    path: "/analytics",
    requiredPermissions: ["data_export.view", "data_export.create"],
    requireAny: true,
    portalType: "school",
    group: "Management",
    order: 54,
  },
  {
    id: "operations",
    label: "Operations Overview",
    icon: "LayoutDashboard",
    path: "/operations",
    requiredPermissions: [
      "reports.view",
      "discipline.view",
      "visitors.view",
      "inventory.view",
    ],
    requireAny: true,
    portalType: "school",
    group: "Operations",
    order: 60,
  },
  {
    id: "welfare",
    label: "Welfare & Discipline",
    icon: "HeartPulse",
    path: "/operations/welfare",
    requiredPermissions: [
      "discipline.view",
      "health_records.view",
      "counseling_records.view",
    ],
    requireAny: true,
    portalType: "school",
    group: "Welfare",
    order: 61,
  },
  {
    id: "discipline",
    label: "Discipline",
    icon: "HeartPulse",
    path: "/operations/welfare",
    requiredPermissions: ["discipline.view"],
    portalType: "school",
    group: "Welfare",
    order: 61.1,
  },
  {
    id: "conduct_records",
    label: "Conduct Records",
    icon: "ClipboardCheck",
    path: "/operations/welfare",
    requiredPermissions: ["conduct_records.view"],
    portalType: "school",
    group: "Welfare",
    order: 61.2,
  },
  {
    id: "counseling_records",
    label: "Counseling Records",
    icon: "HeartPulse",
    path: "/operations/welfare",
    requiredPermissions: ["counseling_records.view"],
    portalType: "school",
    group: "Welfare",
    order: 61.3,
  },
  {
    id: "health_records",
    label: "Health Records",
    icon: "HeartPulse",
    path: "/operations/welfare",
    requiredPermissions: ["health_records.view"],
    portalType: "school",
    group: "Welfare",
    order: 61.4,
  },
  {
    id: "hostel",
    label: "Hostel",
    icon: "Building2",
    path: "/operations/welfare",
    requiredPermissions: ["hostel.view"],
    portalType: "school",
    group: "Welfare",
    order: 61.5,
  },
  {
    id: "operations_academics",
    label: "Lesson Plans & Questions",
    icon: "ClipboardCheck",
    path: "/operations/academics",
    requiredPermissions: ["lesson_plans.view", "question_bank.view"],
    requireAny: true,
    portalType: "school",
    group: "Academic Operations",
    order: 62,
  },
  {
    id: "assignments",
    label: "Assignments",
    icon: "FileText",
    path: "/operations/academics",
    requiredPermissions: ["assignments.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 62.1,
  },
  {
    id: "learning_materials",
    label: "Learning Materials",
    icon: "BookOpen",
    path: "/academics/curriculum",
    requiredPermissions: ["learning_materials.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 62.2,
  },
  {
    id: "academic_calendar",
    label: "Academic Calendar",
    icon: "Calendar",
    path: "/school/configuration/school-calendar",
    requiredPermissions: [
      "academic_calendar.view",
      "config.school_calendar.view",
    ],
    requireAny: true,
    portalType: "school",
    group: "Academic Operations",
    order: 62.3,
  },
  {
    id: "lesson_plans",
    label: "Lesson Plans",
    icon: "ClipboardCheck",
    path: "/operations/academics",
    requiredPermissions: ["lesson_plans.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 62.4,
  },
  {
    id: "question_bank",
    label: "Question Bank",
    icon: "BookMarked",
    path: "/operations/academics",
    requiredPermissions: ["question_bank.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 62.5,
  },
  {
    id: "quizzes",
    label: "Quizzes",
    icon: "FileCheck",
    path: "/operations/academics",
    requiredPermissions: ["quizzes.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 62.6,
  },
  {
    id: "operations_exams",
    label: "Exam Logistics",
    icon: "FileCheck",
    path: "/operations/exams",
    requiredPermissions: [
      "external_exams.view",
      "seating_plan.view",
      "invigilation.view",
    ],
    requireAny: true,
    portalType: "school",
    group: "Academic Operations",
    order: 63,
  },
  {
    id: "exams",
    label: "Exams",
    icon: "FileCheck",
    path: "/academics/results/assessment-format",
    requiredPermissions: ["exams.view", "results.view"],
    requireAny: true,
    portalType: "school",
    group: "Academic Operations",
    hideFromSidebar: true,
    order: 63.1,
  },
  {
    id: "exam_timetable",
    label: "Exam Timetable",
    icon: "Calendar",
    path: "/operations/exams",
    requiredPermissions: ["exam_timetable.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 63.2,
  },
  {
    id: "seating_plan",
    label: "Seating Plan",
    icon: "ClipboardList",
    path: "/operations/exams",
    requiredPermissions: ["seating_plan.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 63.3,
  },
  {
    id: "invigilation",
    label: "Invigilation",
    icon: "UserCheck",
    path: "/operations/exams",
    requiredPermissions: ["invigilation.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 63.4,
  },
  {
    id: "external_exams",
    label: "External Exams",
    icon: "FileCheck",
    path: "/operations/exams",
    requiredPermissions: ["external_exams.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 63.5,
  },
  {
    id: "front_desk",
    label: "Front Desk",
    icon: "UserCog",
    path: "/operations/front-desk",
    requiredPermissions: ["visitors.view", "parent_meetings.view"],
    requireAny: true,
    portalType: "school",
    group: "Operations",
    order: 64,
  },
  {
    id: "visitors",
    label: "Visitors",
    icon: "UserCog",
    path: "/operations/front-desk",
    requiredPermissions: ["visitors.view"],
    portalType: "school",
    group: "Operations",
    order: 64.1,
  },
  {
    id: "parent_meetings",
    label: "Parent Meetings",
    icon: "Users",
    path: "/operations/front-desk",
    requiredPermissions: ["parent_meetings.view"],
    portalType: "school",
    group: "Operations",
    order: 64.2,
  },
  {
    id: "events",
    label: "Events",
    icon: "Flag",
    path: "/operations/front-desk",
    requiredPermissions: ["events.view"],
    portalType: "school",
    group: "Operations",
    order: 64.3,
  },
  {
    id: "assets",
    label: "Assets & Facilities",
    icon: "Package",
    path: "/operations/assets",
    requiredPermissions: [
      "inventory.view",
      "facilities.view",
      "transport.view",
    ],
    requireAny: true,
    portalType: "school",
    group: "Operations",
    order: 65,
  },
  {
    id: "library",
    label: "Library",
    icon: "BookOpen",
    path: "/operations/assets",
    requiredPermissions: ["library.view"],
    portalType: "school",
    group: "Operations",
    order: 65.1,
  },
  {
    id: "transport",
    label: "Transport",
    icon: "Package",
    path: "/operations/assets",
    requiredPermissions: ["transport.view"],
    portalType: "school",
    group: "Operations",
    order: 65.2,
  },
  {
    id: "inventory",
    label: "Inventory",
    icon: "Package",
    path: "/operations/assets",
    requiredPermissions: ["inventory.view"],
    portalType: "school",
    group: "Operations",
    order: 65.3,
  },
  {
    id: "facilities",
    label: "Facilities",
    icon: "Building2",
    path: "/operations/assets",
    requiredPermissions: ["facilities.view"],
    portalType: "school",
    group: "Operations",
    order: 65.4,
  },
  {
    id: "id_cards",
    label: "ID Cards",
    icon: "FileText",
    path: "/operations/assets",
    requiredPermissions: ["id_cards.view", "config.id_card.view"],
    requireAny: true,
    portalType: "school",
    group: "Operations",
    order: 65.5,
  },
  {
    id: "documents",
    label: "Documents",
    icon: "FileText",
    path: "/school/profile",
    requiredPermissions: ["documents.view", "profiles.view_documents"],
    requireAny: true,
    portalType: "school",
    group: "Operations",
    order: 65.6,
  },
  {
    id: "settings",
    label: "Settings",
    icon: "Settings2",
    path: "/settings",
    requiredPermissions: ["settings.view"],
    portalType: "school",
    group: "Management",
    order: 70,
  },
  {
    id: "configuration",
    label: "Configuration",
    icon: "Settings2",
    path: "/school/configuration",
    requiredPermissions: [
      "config.manage",
      "config.sessions_terms.view",
      "config.school_information.view",
      "config.class_levels.view",
      "config.class_arms.view",
      "config.school_calendar.view",
      "config.finance.view",
      "config.subjects.view",
    ],
    requireAny: true,
    portalType: "school",
    group: "Management",
    order: 70.5,
  },
  {
    id: "integrations",
    label: "Integrations",
    icon: "Settings2",
    path: "/settings",
    requiredPermissions: ["integrations.view"],
    portalType: "school",
    group: "Management",
    order: 70.7,
  },
  {
    id: "roles_permissions",
    label: "Roles & Permissions",
    icon: "Lock",
    path: "/school/settings/roles",
    requiredPermissions: ["roles.view"],
    portalType: "school",
    group: "Management",
    order: 71,
  },
  {
    id: "profile",
    label: "My Profile",
    icon: "UserCircle",
    path: "/school/profile",
    requiredPermissions: ["profiles.view_self"],
    portalType: "school",
    group: "Account",
    hideFromSidebar: true,
    order: 72,
  },
  {
    id: "profile_edit_requests",
    label: "Profile Edit Requests",
    icon: "ClipboardCheck",
    path: "/school/profile/edit-requests",
    requiredPermissions: ["profiles.review_edit_requests"],
    portalType: "school",
    group: "Account",
    hideFromSidebar: true,
    order: 72.1,
  },
  {
    id: "my_permissions",
    label: "My Permissions",
    icon: "Key",
    path: "/school/my-permissions",
    requiredPermissions: [],
    portalType: "school",
    group: "Account",
    order: 73,
  },

  {
    id: "student_home",
    label: "Dashboard",
    icon: "LayoutDashboard",
    path: "/portals/student",
    requiredPermissions: [],
    portalType: "school",
    group: "Student Portal",
    order: 100,
  },
  {
    id: "student_profile",
    label: "My Profile",
    icon: "Users",
    path: "/portals/student/profile",
    requiredPermissions: [],
    portalType: "school",
    group: "Student Portal",
    order: 101,
  },
  {
    id: "student_attendance",
    label: "Attendance",
    icon: "ClipboardCheck",
    path: "/portals/student/attendance",
    requiredPermissions: ["attendance.view"],
    portalType: "school",
    group: "Student Portal",
    order: 102,
  },
  {
    id: "student_results",
    label: "Results",
    icon: "Award",
    path: "/portals/student/results",
    requiredPermissions: ["results.view"],
    portalType: "school",
    group: "Student Portal",
    order: 103,
  },
  {
    id: "student_curriculum",
    label: "My Subjects",
    icon: "BookOpen",
    path: "/my-subjects",
    requiredPermissions: [],
    portalType: "school",
    group: "Student Portal",
    order: 104,
  },
  {
    id: "student_curriculum_legacy",
    label: "Scheme of Work",
    icon: "BookOpen",
    path: "/portals/student/curriculum",
    requiredPermissions: [],
    portalType: "school",
    group: "Student Portal",
    hideFromSidebar: true,
    order: 104.1,
  },
  {
    id: "student_timetable",
    label: "Timetable",
    icon: "Calendar",
    path: "/portals/student/timetable",
    requiredPermissions: ["timetable.view"],
    portalType: "school",
    group: "Student Portal",
    order: 105,
  },
  {
    id: "student_assignments",
    label: "Assignments",
    icon: "FileText",
    path: "/portals/student/assignments",
    requiredPermissions: ["assignments.view"],
    portalType: "school",
    group: "Student Portal",
    order: 106,
  },
  {
    id: "student_fees",
    label: "Fees",
    icon: "CreditCard",
    path: "/portals/student/fees",
    requiredPermissions: ["fees.view"],
    portalType: "school",
    group: "Student Portal",
    order: 107,
  },
  {
    id: "student_services",
    label: "Services",
    icon: "Building2",
    path: "/portals/student/services",
    requiredPermissions: [],
    portalType: "school",
    group: "Student Portal",
    order: 108,
  },
  {
    id: "student_announcements",
    label: "Announcements",
    icon: "Megaphone",
    path: "/portals/student/announcements",
    requiredPermissions: ["announcements.view"],
    portalType: "school",
    group: "Student Portal",
    order: 109,
  },
  {
    id: "student_notifications",
    label: "Notifications",
    icon: "BellRing",
    path: "/portals/student/notifications",
    requiredPermissions: [],
    portalType: "school",
    group: "Student Portal",
    order: 110,
  },

  {
    id: "parent_home",
    label: "Dashboard",
    icon: "LayoutDashboard",
    path: "/portals/parent",
    requiredPermissions: [],
    portalType: "school",
    group: "Parent Portal",
    order: 120,
  },
  {
    id: "parent_children",
    label: "My Children",
    icon: "Users",
    path: "/portals/parent/children",
    requiredPermissions: [],
    portalType: "school",
    group: "Parent Portal",
    order: 121,
  },
  {
    id: "parent_announcements",
    label: "Announcements",
    icon: "Megaphone",
    path: "/portals/parent/announcements",
    requiredPermissions: ["announcements.view"],
    portalType: "school",
    group: "Parent Portal",
    order: 122,
  },
  {
    id: "parent_curriculum",
    label: "Scheme of Work",
    icon: "BookOpen",
    path: "/portals/parent/curriculum",
    requiredPermissions: [],
    portalType: "school",
    group: "Parent Portal",
    hideFromSidebar: true,
    order: 123,
  },
  {
    id: "parent_children_subjects",
    label: "Child Subjects",
    icon: "BookOpen",
    path: "/my-children",
    requiredPermissions: [],
    portalType: "school",
    group: "Parent Portal",
    hideFromSidebar: true,
    order: 123.1,
  },
  {
    id: "parent_notifications",
    label: "Notifications",
    icon: "BellRing",
    path: "/portals/parent/notifications",
    requiredPermissions: [],
    portalType: "school",
    group: "Parent Portal",
    order: 124,
  },
  {
    id: "parent_profile",
    label: "Profile",
    icon: "Users",
    path: "/portals/parent/profile",
    requiredPermissions: [],
    portalType: "school",
    group: "Parent Portal",
    order: 125,
  },

  {
    id: "teacher_home",
    label: "Dashboard",
    icon: "LayoutDashboard",
    path: "/portals/teacher",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    order: 140,
  },
  {
    id: "teacher_classes",
    label: "My Classes",
    icon: "Users",
    path: "/portals/teacher/classes",
    requiredPermissions: [],
    portalType: "school",
    group: "My Classes",
    order: 141,
  },
  {
    id: "teacher_attendance",
    label: "Mark Attendance",
    icon: "ClipboardCheck",
    path: "/portals/teacher/attendance",
    requiredPermissions: ["attendance.mark", "attendance.view"],
    requireAny: true,
    portalType: "school",
    group: "Attendance",
    order: 142,
  },
  {
    id: "teacher_attendance_history",
    label: "Attendance History",
    icon: "History",
    path: "/portals/teacher/attendance/history",
    requiredPermissions: ["attendance.mark", "attendance.view"],
    requireAny: true,
    portalType: "school",
    group: "Attendance",
    order: 142.1,
  },
  {
    id: "teacher_attendance_reports",
    label: "Attendance Reports",
    icon: "BarChart3",
    path: "/portals/teacher/attendance/reports",
    requiredPermissions: ["attendance.mark", "attendance.view"],
    requireAny: true,
    portalType: "school",
    group: "Attendance",
    order: 142.2,
  },
  {
    id: "teacher_gradebook",
    label: "Gradebook",
    icon: "Grid2x2",
    path: "/portals/teacher/gradebook",
    requiredPermissions: ["results.create", "results.edit"],
    requireAny: true,
    portalType: "school",
    group: "My Classes",
    order: 142.5,
  },
  {
    id: "teacher_scores",
    label: "Enter Scores",
    icon: "Award",
    path: "/portals/teacher/scores",
    requiredPermissions: ["results.create", "results.edit"],
    requireAny: true,
    portalType: "school",
    group: "My Classes",
    hideFromSidebar: true,
    order: 143,
  },
  {
    id: "teacher_content_overview",
    label: "Content Studio",
    icon: "Layers3",
    path: "/portals/teacher/content",
    requiredPermissions: ["subjects.view", "results.create", "results.edit", "assignments.view", "assignments.create"],
    requireAny: true,
    portalType: "school",
    group: "Content",
    hideFromSidebar: true,
    order: 143.95,
  },
  {
    id: "teacher_curriculum",
    label: "Lesson Notes",
    icon: "BookOpen",
    path: "/portals/teacher/content/lesson-notes",
    requiredPermissions: ["subjects.view", "results.create", "results.edit", "assignments.view", "assignments.create"],
    requireAny: true,
    portalType: "school",
    group: "Content",
    order: 144,
  },
  {
    id: "teacher_scheme_of_work",
    label: "Scheme of Work",
    icon: "BookOpen",
    path: "/portals/teacher/content/scheme-of-work",
    requiredPermissions: ["subjects.view", "results.create", "results.edit", "assignments.view", "assignments.create"],
    requireAny: true,
    portalType: "school",
    group: "Content",
    order: 144.05,
  },
  {
    id: "teacher_curriculum_legacy",
    label: "Scheme of Work",
    icon: "BookOpen",
    path: "/portals/teacher/curriculum",
    requiredPermissions: ["subjects.view", "results.create", "results.edit", "assignments.view", "assignments.create"],
    requireAny: true,
    portalType: "school",
    group: "Content",
    hideFromSidebar: true,
    order: 144.1,
  },
  {
    id: "teacher_subjects_legacy",
    label: "My Subjects",
    icon: "BookOpen",
    path: "/my-subjects",
    requiredPermissions: ["subjects.view", "results.create", "results.edit", "assignments.view", "assignments.create"],
    requireAny: true,
    portalType: "school",
    group: "Content",
    hideFromSidebar: true,
    order: 144.2,
  },
  {
    id: "teacher_clock",
    label: "Clock In / Out",
    icon: "UserCheck",
    path: "/portals/teacher/staff-attendance",
    requiredPermissions: [],
    portalType: "school",
    group: "Teacher Portal",
    hideFromSidebar: true,
    order: 145,
  },
  {
    id: "teacher_training",
    label: "Training",
    icon: "ClipboardList",
    path: "/portals/teacher/training",
    requiredPermissions: [],
    portalType: "school",
    group: "Teacher Portal",
    hideFromSidebar: true,
    order: 146,
  },
  {
    id: "teacher_assignments",
    label: "Assignments",
    icon: "FileText",
    path: "/portals/teacher/assignments",
    requiredPermissions: ["assignments.view", "assignments.create"],
    requireAny: true,
    portalType: "school",
    group: "My Classes",
    order: 147,
  },
  {
    id: "teacher_announcements",
    label: "Announcements",
    icon: "Megaphone",
    path: "/portals/teacher/announcements",
    requiredPermissions: ["announcements.view"],
    portalType: "school",
    group: "Teacher Portal",
    hideFromSidebar: true,
    order: 147.1,
  },
  {
    id: "teacher_notifications",
    label: "Notifications",
    icon: "BellRing",
    path: "/portals/teacher/notifications",
    requiredPermissions: [],
    portalType: "school",
    group: "Teacher Portal",
    hideFromSidebar: true,
    order: 147.2,
  },
  {
    id: "teacher_profile",
    label: "Profile",
    icon: "User",
    path: "/portals/teacher/profile",
    requiredPermissions: [],
    portalType: "school",
    group: "Teacher Portal",
    hideFromSidebar: true,
    order: 147.25,
  },
  {
    id: "teacher_timetable",
    label: "Timetable",
    icon: "Calendar",
    path: "/portals/teacher/timetable",
    requiredPermissions: ["timetable.view"],
    portalType: "school",
    group: "Overview",
    order: 148,
  },
  {
    id: "principal_home",
    label: "Executive Dashboard",
    icon: "LayoutDashboard",
    path: "/portals/principal",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    order: 158,
  },
  {
    id: "principal_approvals",
    label: "Pending Approvals",
    icon: "ShieldCheck",
    path: "/portals/principal/approvals",
    requiredPermissions: ["results.approve"],
    portalType: "school",
    group: "Approvals",
    order: 158.1,
  },
  {
    id: "principal_academics",
    label: "Academic Performance",
    icon: "BarChart3",
    path: "/portals/principal/academics/performance",
    requiredPermissions: ["results.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 158.2,
  },
  {
    id: "principal_promotions",
    label: "Student Promotions",
    icon: "GraduationCap",
    path: "/portals/principal/academics/promotions",
    requiredPermissions: ["students.view", "results.view"],
    requireAny: true,
    portalType: "school",
    group: "Academic Operations",
    order: 158.3,
  },
  {
    id: "principal_report_comments",
    label: "Report Card Comments",
    icon: "FileText",
    path: "/portals/principal/academics/report-comments",
    requiredPermissions: ["results.view"],
    portalType: "school",
    group: "Academic Operations",
    order: 158.4,
  },
  {
    id: "principal_staff",
    label: "Staff Management",
    icon: "Users",
    path: "/portals/principal/people/staff",
    requiredPermissions: ["teachers.view", "staff.view"],
    requireAny: true,
    portalType: "school",
    group: "People",
    order: 158.5,
  },
  {
    id: "principal_students",
    label: "Student Overview",
    icon: "UserCheck",
    path: "/portals/principal/people/students",
    requiredPermissions: ["students.view"],
    portalType: "school",
    group: "People",
    order: 158.55,
  },
  {
    id: "principal_discipline",
    label: "Disciplinary Records",
    icon: "Flag",
    path: "/portals/principal/people/discipline",
    requiredPermissions: ["discipline.view"],
    portalType: "school",
    group: "People",
    order: 158.6,
  },
  {
    id: "principal_leave_requests",
    label: "Leave Requests",
    icon: "Calendar",
    path: "/portals/principal/people/leaves",
    requiredPermissions: ["staff_leave.view"],
    portalType: "school",
    group: "People",
    order: 158.7,
  },
  {
    id: "principal_announcements",
    label: "Announcements",
    icon: "Megaphone",
    path: "/portals/principal/communication/announcements",
    requiredPermissions: ["announcements.view"],
    portalType: "school",
    group: "Communication",
    order: 158.8,
  },
  {
    id: "principal_broadcast",
    label: "Parent Broadcast",
    icon: "BellRing",
    path: "/portals/principal/communication/broadcast",
    requiredPermissions: ["announcements.view", "messaging.send"],
    requireAny: true,
    portalType: "school",
    group: "Communication",
    order: 158.9,
  },
  {
    id: "principal_events",
    label: "Events & Calendar",
    icon: "CalendarDays",
    path: "/portals/principal/operations/events",
    requiredPermissions: ["config.school_calendar.view", "events.view"],
    requireAny: true,
    portalType: "school",
    group: "Operations",
    order: 159,
  },
  {
    id: "principal_visitors",
    label: "Visitor Log",
    icon: "Building2",
    path: "/portals/principal/operations/visitors",
    requiredPermissions: ["visitors.view"],
    portalType: "school",
    group: "Operations",
    order: 159.1,
  },
  {
    id: "principal_analytics",
    label: "School Analytics",
    icon: "BarChart3",
    path: "/portals/principal/reports/analytics",
    requiredPermissions: ["reports.view"],
    portalType: "school",
    group: "Reports",
    order: 159.2,
  },
  {
    id: "principal_finance",
    label: "Financial Summary",
    icon: "CreditCard",
    path: "/portals/principal/reports/finance",
    requiredPermissions: ["fees.view", "expenses.view", "reports.view"],
    requireAny: true,
    portalType: "school",
    group: "Reports",
    order: 159.25,
  },
  {
    id: "principal_settings",
    label: "School Settings",
    icon: "Settings2",
    path: "/portals/principal/settings",
    requiredPermissions: ["config.school_information.view"],
    portalType: "school",
    group: "Management",
    order: 159.3,
  },
  {
    id: "principal_profile",
    label: "Profile",
    icon: "UserCircle",
    path: "/portals/principal/profile",
    requiredPermissions: [],
    portalType: "school",
    group: "Account",
    hideFromSidebar: true,
    order: 159.4,
  },
  {
    id: "admission_officer_home",
    label: "Dashboard",
    icon: "LayoutDashboard",
    path: "/portals/admission-officer",
    requiredPermissions: [],
    portalType: "school",
    group: "Admissions Portal",
    order: 150,
  },
  {
    id: "admission_officer_applications",
    label: "Applications",
    icon: "Users",
    path: "/portals/admission-officer/applications",
    requiredPermissions: ["admissions.view"],
    portalType: "school",
    group: "Admissions Portal",
    order: 151,
  },
  {
    id: "admission_officer_pipeline",
    label: "Pipeline",
    icon: "ClipboardList",
    path: "/portals/admission-officer/pipeline",
    requiredPermissions: ["admissions.view"],
    portalType: "school",
    group: "Admissions Portal",
    order: 152,
  },
  {
    id: "admission_officer_screenings",
    label: "Screening Desk",
    icon: "FileCheck",
    path: "/portals/admission-officer/screenings",
    requiredPermissions: ["admissions.edit"],
    portalType: "school",
    group: "Admissions Portal",
    order: 153,
  },
  {
    id: "admission_officer_offers",
    label: "Offers",
    icon: "FileText",
    path: "/portals/admission-officer/offers",
    requiredPermissions: ["admissions.approve"],
    portalType: "school",
    group: "Admissions Portal",
    order: 154,
  },
  {
    id: "admission_officer_enrollment",
    label: "Ready To Enroll",
    icon: "UserCheck",
    path: "/portals/admission-officer/ready-to-enroll",
    requiredPermissions: ["admissions.enroll"],
    portalType: "school",
    group: "Admissions Portal",
    order: 155,
  },
  {
    id: "admission_officer_analytics",
    label: "Analytics",
    icon: "BarChart3",
    path: "/portals/admission-officer/analytics",
    requiredPermissions: ["reports.view"],
    portalType: "school",
    group: "Admissions Portal",
    order: 156,
  },
  {
    id: "admission_officer_settings",
    label: "Settings",
    icon: "Settings2",
    path: "/portals/admission-officer/settings",
    requiredPermissions: ["admissions.edit"],
    portalType: "school",
    group: "Admissions Portal",
    order: 157,
  },
  {
    id: "admission_officer_profile",
    label: "Profile",
    icon: "UserCircle",
    path: "/portals/admission-officer/profile",
    requiredPermissions: [],
    portalType: "school",
    group: "Admissions Portal",
    hideFromSidebar: true,
    order: 157.1,
  },
  {
    id: "exam_officer_home",
    label: "Dashboard",
    icon: "LayoutDashboard",
    path: "/portals/exam-officer",
    requiredPermissions: [],
    portalType: "school",
    group: "Exam Portal",
    order: 160,
  },
  {
    id: "exam_officer_exams",
    label: "All Exams",
    icon: "FileCheck",
    path: "/portals/exam-officer/exams",
    requiredPermissions: ["exams.view"],
    portalType: "school",
    group: "Exam Portal",
    order: 161,
  },
  {
    id: "exam_officer_score_status",
    label: "Score Entry Status",
    icon: "ClipboardCheck",
    path: "/portals/exam-officer/score-entry-status",
    requiredPermissions: ["results.compile", "results.edit", "results.create"],
    requireAny: true,
    portalType: "school",
    group: "Exam Portal",
    order: 162,
  },
  {
    id: "exam_officer_timetable",
    label: "Exam Timetable",
    icon: "CalendarDays",
    path: "/portals/exam-officer/timetable",
    requiredPermissions: ["exam_timetable.view"],
    portalType: "school",
    group: "Exam Portal",
    order: 163,
  },
  {
    id: "exam_officer_publication",
    label: "Publication Control",
    icon: "Send",
    path: "/portals/exam-officer/publication",
    requiredPermissions: ["results.publish", "results.approve", "results.compile"],
    requireAny: true,
    portalType: "school",
    group: "Exam Portal",
    order: 164,
  },
  {
    id: "exam_officer_question_bank",
    label: "Question Bank",
    icon: "Brain",
    path: "/portals/exam-officer/question-bank",
    requiredPermissions: ["question_bank.view"],
    portalType: "school",
    group: "Exam Portal",
    order: 165,
  },
  {
    id: "exam_officer_broadsheet_alias",
    label: "Broadsheet",
    icon: "Award",
    path: "/academics/results/broadsheets",
    requiredPermissions: ["results.view", "results.compile"],
    requireAny: true,
    portalType: "school",
    group: "Exam Portal",
    hideFromSidebar: true,
    order: 165.1,
  },
  {
    id: "exam_officer_report_cards_alias",
    label: "Report Cards",
    icon: "FileText",
    path: "/academics/results/report-cards",
    requiredPermissions: ["results.view", "results.export"],
    requireAny: true,
    portalType: "school",
    group: "Exam Portal",
    hideFromSidebar: true,
    order: 165.2,
  },
  {
    id: "exam_officer_analytics_alias",
    label: "Analytics",
    icon: "BarChart3",
    path: "/academics/results/analytics",
    requiredPermissions: ["reports.view", "results.view"],
    requireAny: true,
    portalType: "school",
    group: "Exam Portal",
    hideFromSidebar: true,
    order: 165.3,
  },
  {
    id: "exam_officer_assessment_alias",
    label: "Grading Systems",
    icon: "Settings2",
    path: "/academics/results/assessment-format",
    requiredPermissions: ["settings.grading", "results.compile", "exams.view"],
    requireAny: true,
    portalType: "school",
    group: "Exam Portal",
    hideFromSidebar: true,
    order: 165.4,
  },
  {
    id: "exam_officer_profile",
    label: "Profile",
    icon: "User",
    path: "/portals/exam-officer/profile",
    requiredPermissions: [],
    portalType: "school",
    group: "Exam Portal",
    hideFromSidebar: true,
    order: 165.5,
  },
  {
    id: "nurse_dashboard",
    label: "Dashboard",
    icon: "LayoutDashboard",
    path: "/portals/nurse",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    order: 170,
  },
  {
    id: "nurse_queue",
    label: "Clinic Queue",
    icon: "ClipboardList",
    path: "/portals/nurse/queue",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    order: 171,
  },
  {
    id: "nurse_log_visit",
    label: "Log Visit",
    icon: "HeartPulse",
    path: "/portals/nurse/log-visit",
    requiredPermissions: [],
    portalType: "school",
    group: "Patients",
    order: 172,
  },
  {
    id: "nurse_visit_history",
    label: "Visit History",
    icon: "FileText",
    path: "/portals/nurse/visit-history",
    requiredPermissions: [],
    portalType: "school",
    group: "Patients",
    order: 173,
  },
  {
    id: "nurse_profiles",
    label: "Health Profiles",
    icon: "Users",
    path: "/portals/nurse/health-profiles",
    requiredPermissions: [],
    portalType: "school",
    group: "Patients",
    order: 174,
  },
  {
    id: "nurse_sick_leave",
    label: "Sick Leave",
    icon: "FileCheck",
    path: "/portals/nurse/sick-leave",
    requiredPermissions: [],
    portalType: "school",
    group: "Patients",
    order: 175,
  },
  {
    id: "nurse_log_emergency",
    label: "Log Emergency",
    icon: "ShieldCheck",
    path: "/portals/nurse/log-emergency",
    requiredPermissions: [],
    portalType: "school",
    group: "Emergencies",
    order: 176,
  },
  {
    id: "nurse_emergency_log",
    label: "Emergency Log",
    icon: "FileClock",
    path: "/portals/nurse/emergency-log",
    requiredPermissions: [],
    portalType: "school",
    group: "Emergencies",
    order: 177,
  },
  {
    id: "nurse_inventory",
    label: "Inventory",
    icon: "Package",
    path: "/portals/nurse/inventory",
    requiredPermissions: [],
    portalType: "school",
    group: "Medical Supplies",
    order: 178,
  },
  {
    id: "nurse_low_stock",
    label: "Low Stock Alerts",
    icon: "AlertCircle",
    path: "/portals/nurse/low-stock",
    requiredPermissions: [],
    portalType: "school",
    group: "Medical Supplies",
    order: 179,
  },
  {
    id: "nurse_transactions",
    label: "Transactions",
    icon: "FileText",
    path: "/portals/nurse/transactions",
    requiredPermissions: [],
    portalType: "school",
    group: "Medical Supplies",
    order: 180,
  },
  {
    id: "nurse_schedule_screening",
    label: "Schedule Screening",
    icon: "Calendar",
    path: "/portals/nurse/schedule-screening",
    requiredPermissions: [],
    portalType: "school",
    group: "Screenings",
    order: 181,
  },
  {
    id: "nurse_screening_records",
    label: "Screening Records",
    icon: "ClipboardCheck",
    path: "/portals/nurse/screening-records",
    requiredPermissions: [],
    portalType: "school",
    group: "Screenings",
    order: 182,
  },
  {
    id: "nurse_health_summary",
    label: "Health Summary",
    icon: "BarChart3",
    path: "/portals/nurse/health-summary",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 183,
  },
  {
    id: "nurse_common_conditions",
    label: "Common Conditions",
    icon: "BarChart3",
    path: "/portals/nurse/common-conditions",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 184,
  },
  {
    id: "nurse_inventory_report",
    label: "Inventory Report",
    icon: "FileText",
    path: "/portals/nurse/inventory-report",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 185,
  },
  {
    id: "nurse_export_records",
    label: "Export Records",
    icon: "FileText",
    path: "/portals/nurse/export-records",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 186,
  },
  {
    id: "nurse_profile",
    label: "Profile",
    icon: "User",
    path: "/portals/nurse/profile",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    hideFromSidebar: true,
    order: 186.5,
  },
  {
    id: "librarian_dashboard",
    label: "Dashboard",
    icon: "LayoutDashboard",
    path: "/portals/librarian",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    order: 190,
  },
  {
    id: "library_issue",
    label: "Issue Book",
    icon: "BookMarked",
    path: "/portals/librarian/issue-book",
    requiredPermissions: [],
    portalType: "school",
    group: "Circulation",
    order: 191,
  },
  {
    id: "library_return",
    label: "Return Book",
    icon: "BookOpen",
    path: "/portals/librarian/return-book",
    requiredPermissions: [],
    portalType: "school",
    group: "Circulation",
    order: 192,
  },
  {
    id: "library_loans",
    label: "Active Loans",
    icon: "ClipboardList",
    path: "/portals/librarian/active-loans",
    requiredPermissions: [],
    portalType: "school",
    group: "Circulation",
    order: 193,
  },
  {
    id: "library_overdue",
    label: "Overdue Loans",
    icon: "AlertCircle",
    path: "/portals/librarian/overdue-loans",
    requiredPermissions: [],
    portalType: "school",
    group: "Circulation",
    order: 194,
  },
  {
    id: "library_books",
    label: "All Books",
    icon: "BookOpen",
    path: "/portals/librarian/all-books",
    requiredPermissions: [],
    portalType: "school",
    group: "Catalog",
    order: 195,
  },
  {
    id: "library_add_book",
    label: "Add Book",
    icon: "UserPlus",
    path: "/portals/librarian/add-book",
    requiredPermissions: [],
    portalType: "school",
    group: "Catalog",
    order: 196,
  },
  {
    id: "library_digital_resources",
    label: "Digital Resources",
    icon: "FileText",
    path: "/portals/librarian/digital-resources",
    requiredPermissions: [],
    portalType: "school",
    group: "Catalog",
    order: 197,
  },
  {
    id: "library_members",
    label: "All Members",
    icon: "Users",
    path: "/portals/librarian/all-members",
    requiredPermissions: [],
    portalType: "school",
    group: "Members",
    order: 198,
  },
  {
    id: "library_reservations",
    label: "Reservations",
    icon: "Calendar",
    path: "/portals/librarian/reservations",
    requiredPermissions: [],
    portalType: "school",
    group: "Members",
    order: 199,
  },
  {
    id: "library_fines",
    label: "Fines & Payments",
    icon: "CreditCard",
    path: "/portals/librarian/fines-payments",
    requiredPermissions: [],
    portalType: "school",
    group: "Members",
    order: 200,
  },
  {
    id: "library_programs",
    label: "Reading Programs",
    icon: "Award",
    path: "/portals/librarian/reading-programs",
    requiredPermissions: [],
    portalType: "school",
    group: "Programs",
    order: 201,
  },
  {
    id: "library_circulation_report",
    label: "Circulation Report",
    icon: "BarChart3",
    path: "/portals/librarian/circulation-report",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 202,
  },
  {
    id: "library_popular_books",
    label: "Popular Books",
    icon: "BarChart3",
    path: "/portals/librarian/popular-books",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 203,
  },
  {
    id: "library_inventory_report",
    label: "Inventory Report",
    icon: "FileText",
    path: "/portals/librarian/inventory-report",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 204,
  },
  {
    id: "library_settings",
    label: "Library Settings",
    icon: "Settings2",
    path: "/portals/librarian/library-settings",
    requiredPermissions: [],
    portalType: "school",
    group: "Management",
    order: 205,
  },
  {
    id: "library_fine_rules",
    label: "Fine Rules",
    icon: "Settings2",
    path: "/portals/librarian/fine-rules",
    requiredPermissions: [],
    portalType: "school",
    group: "Management",
    order: 206,
  },
  {
    id: "library_profile",
    label: "Profile",
    icon: "User",
    path: "/portals/librarian/profile",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    hideFromSidebar: true,
    order: 206.5,
  },
  {
    id: "front_desk_dashboard",
    label: "Dashboard",
    icon: "LayoutDashboard",
    path: "/portals/front-desk",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    order: 210,
  },
  {
    id: "front_desk_check_in",
    label: "Check In Visitor",
    icon: "UserCheck",
    path: "/portals/front-desk/check-in-visitor",
    requiredPermissions: [],
    portalType: "school",
    group: "Visitors",
    order: 211,
  },
  {
    id: "front_desk_active_visitors",
    label: "Active Visitors",
    icon: "Users",
    path: "/portals/front-desk/active-visitors",
    requiredPermissions: [],
    portalType: "school",
    group: "Visitors",
    order: 212,
  },
  {
    id: "front_desk_visitor_history",
    label: "Visitor History",
    icon: "FileClock",
    path: "/portals/front-desk/visitor-history",
    requiredPermissions: [],
    portalType: "school",
    group: "Visitors",
    order: 213,
  },
  {
    id: "front_desk_late_arrivals",
    label: "Late Arrivals",
    icon: "Clock",
    path: "/portals/front-desk/late-arrivals",
    requiredPermissions: [],
    portalType: "school",
    group: "Students",
    order: 214,
  },
  {
    id: "front_desk_early_departures",
    label: "Early Departures",
    icon: "CalendarOff",
    path: "/portals/front-desk/early-departures",
    requiredPermissions: [],
    portalType: "school",
    group: "Students",
    order: 215,
  },
  {
    id: "front_desk_student_movements",
    label: "Student Movements",
    icon: "ClipboardList",
    path: "/portals/front-desk/student-movements",
    requiredPermissions: [],
    portalType: "school",
    group: "Students",
    order: 216,
  },
  {
    id: "front_desk_receive_parcel",
    label: "Receive Parcel",
    icon: "Package",
    path: "/portals/front-desk/receive-parcel",
    requiredPermissions: [],
    portalType: "school",
    group: "Parcels & Mail",
    order: 217,
  },
  {
    id: "front_desk_parcel_tracking",
    label: "Parcel Tracking",
    icon: "Package",
    path: "/portals/front-desk/parcel-tracking",
    requiredPermissions: [],
    portalType: "school",
    group: "Parcels & Mail",
    order: 218,
  },
  {
    id: "front_desk_log_item",
    label: "Log Item",
    icon: "Package",
    path: "/portals/front-desk/log-item",
    requiredPermissions: [],
    portalType: "school",
    group: "Lost & Found",
    order: 219,
  },
  {
    id: "front_desk_all_items",
    label: "All Items",
    icon: "Package",
    path: "/portals/front-desk/all-items",
    requiredPermissions: [],
    portalType: "school",
    group: "Lost & Found",
    order: 220,
  },
  {
    id: "front_desk_room_availability",
    label: "Room Availability",
    icon: "Building2",
    path: "/portals/front-desk/room-availability",
    requiredPermissions: [],
    portalType: "school",
    group: "Meeting Rooms",
    order: 221,
  },
  {
    id: "front_desk_book_room",
    label: "Book a Room",
    icon: "Calendar",
    path: "/portals/front-desk/book-a-room",
    requiredPermissions: [],
    portalType: "school",
    group: "Meeting Rooms",
    order: 222,
  },
  {
    id: "front_desk_bookings_calendar",
    label: "Bookings Calendar",
    icon: "Calendar",
    path: "/portals/front-desk/bookings-calendar",
    requiredPermissions: [],
    portalType: "school",
    group: "Meeting Rooms",
    order: 223,
  },
  {
    id: "front_desk_call_log",
    label: "Call Log",
    icon: "Headphones",
    path: "/portals/front-desk/call-log",
    requiredPermissions: [],
    portalType: "school",
    group: "Calls & Messages",
    order: 224,
  },
  {
    id: "front_desk_pending_callbacks",
    label: "Pending Callbacks",
    icon: "Phone",
    path: "/portals/front-desk/pending-callbacks",
    requiredPermissions: [],
    portalType: "school",
    group: "Calls & Messages",
    order: 225,
  },
  {
    id: "front_desk_daily_report",
    label: "Daily Activity Report",
    icon: "BarChart3",
    path: "/portals/front-desk/daily-activity-report",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 226,
  },
  {
    id: "front_desk_visitor_report",
    label: "Visitor Report",
    icon: "FileText",
    path: "/portals/front-desk/visitor-report",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 227,
  },
  {
    id: "front_desk_movement_report",
    label: "Movement Report",
    icon: "FileText",
    path: "/portals/front-desk/movement-report",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 228,
  },
  {
    id: "front_desk_profile",
    label: "Profile",
    icon: "User",
    path: "/portals/front-desk/profile",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    hideFromSidebar: true,
    order: 228.5,
  },
  {
    id: "hostel_dashboard",
    label: "Dashboard",
    icon: "LayoutDashboard",
    path: "/portals/hostel",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    order: 230,
  },
  {
    id: "hostel_boarders",
    label: "All Boarders",
    icon: "Users",
    path: "/portals/hostel/all-boarders",
    requiredPermissions: [],
    portalType: "school",
    group: "Boarders",
    order: 231,
  },
  {
    id: "hostel_room_map",
    label: "Room & Bed Map",
    icon: "Building2",
    path: "/portals/hostel/room-bed-map",
    requiredPermissions: [],
    portalType: "school",
    group: "Boarders",
    order: 232,
  },
  {
    id: "hostel_assign_beds",
    label: "Assign Beds",
    icon: "UserPlus",
    path: "/portals/hostel/assign-beds",
    requiredPermissions: [],
    portalType: "school",
    group: "Boarders",
    order: 233,
  },
  {
    id: "hostel_take_roll_call",
    label: "Take Roll Call",
    icon: "ClipboardCheck",
    path: "/portals/hostel/take-roll-call",
    requiredPermissions: [],
    portalType: "school",
    group: "Attendance",
    order: 234,
  },
  {
    id: "hostel_attendance_history",
    label: "Attendance History",
    icon: "FileClock",
    path: "/portals/hostel/attendance-history",
    requiredPermissions: [],
    portalType: "school",
    group: "Attendance",
    order: 235,
  },
  {
    id: "hostel_absentees",
    label: "Absentees Report",
    icon: "AlertCircle",
    path: "/portals/hostel/absentees-report",
    requiredPermissions: [],
    portalType: "school",
    group: "Attendance",
    order: 236,
  },
  {
    id: "hostel_pending_exeats",
    label: "Pending Exeats",
    icon: "Calendar",
    path: "/portals/hostel/pending-exeats",
    requiredPermissions: [],
    portalType: "school",
    group: "Exeat",
    order: 237,
  },
  {
    id: "hostel_log_exeat",
    label: "Log Exeat",
    icon: "FileText",
    path: "/portals/hostel/log-exeat",
    requiredPermissions: [],
    portalType: "school",
    group: "Exeat",
    order: 238,
  },
  {
    id: "hostel_overdue_returns",
    label: "Overdue Returns",
    icon: "AlertCircle",
    path: "/portals/hostel/overdue-returns",
    requiredPermissions: [],
    portalType: "school",
    group: "Exeat",
    order: 239,
  },
  {
    id: "hostel_exeat_history",
    label: "Exeat History",
    icon: "FileClock",
    path: "/portals/hostel/exeat-history",
    requiredPermissions: [],
    portalType: "school",
    group: "Exeat",
    order: 240,
  },
  {
    id: "hostel_log_incident",
    label: "Log Incident",
    icon: "ShieldCheck",
    path: "/portals/hostel/log-incident",
    requiredPermissions: [],
    portalType: "school",
    group: "Incidents",
    order: 241,
  },
  {
    id: "hostel_incidents",
    label: "All Incidents",
    icon: "FileText",
    path: "/portals/hostel/all-incidents",
    requiredPermissions: [],
    portalType: "school",
    group: "Incidents",
    order: 242,
  },
  {
    id: "hostel_submit_request",
    label: "Submit Request",
    icon: "ClipboardList",
    path: "/portals/hostel/submit-request",
    requiredPermissions: [],
    portalType: "school",
    group: "Maintenance",
    order: 243,
  },
  {
    id: "hostel_requests",
    label: "All Requests",
    icon: "ClipboardList",
    path: "/portals/hostel/all-requests",
    requiredPermissions: [],
    portalType: "school",
    group: "Maintenance",
    order: 244,
  },
  {
    id: "hostel_timetable",
    label: "Hostel Timetable",
    icon: "Calendar",
    path: "/portals/hostel/hostel-timetable",
    requiredPermissions: [],
    portalType: "school",
    group: "Schedules",
    order: 245,
  },
  {
    id: "hostel_edit_schedule",
    label: "Edit Schedule",
    icon: "Settings2",
    path: "/portals/hostel/edit-schedule",
    requiredPermissions: [],
    portalType: "school",
    group: "Schedules",
    order: 246,
  },
  {
    id: "hostel_attendance_report",
    label: "Attendance Report",
    icon: "BarChart3",
    path: "/portals/hostel/attendance-report",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 247,
  },
  {
    id: "hostel_occupancy_report",
    label: "Occupancy Report",
    icon: "BarChart3",
    path: "/portals/hostel/occupancy-report",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 248,
  },
  {
    id: "hostel_exeat_report",
    label: "Exeat Report",
    icon: "FileText",
    path: "/portals/hostel/exeat-report",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 249,
  },
  {
    id: "hostel_incident_report",
    label: "Incident Report",
    icon: "FileText",
    path: "/portals/hostel/incident-report",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 250,
  },
  {
    id: "hostel_profile",
    label: "Profile",
    icon: "User",
    path: "/portals/hostel/profile",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    hideFromSidebar: true,
    order: 250.5,
  },
  {
    id: "transport_dashboard",
    label: "Dashboard",
    icon: "LayoutDashboard",
    path: "/portals/transport",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    order: 255,
  },
  {
    id: "transport_live_map",
    label: "Live Route Map",
    icon: "MapPinned",
    path: "/portals/transport/live-route-map",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    order: 256,
  },
  {
    id: "transport_vehicles",
    label: "Vehicles",
    icon: "Package",
    path: "/portals/transport/vehicles",
    requiredPermissions: [],
    portalType: "school",
    group: "Fleet",
    order: 257,
  },
  {
    id: "transport_compliance",
    label: "Compliance Alerts",
    icon: "ShieldCheck",
    path: "/portals/transport/compliance-alerts",
    requiredPermissions: [],
    portalType: "school",
    group: "Fleet",
    order: 258,
  },
  {
    id: "transport_fuel_logs",
    label: "Fuel Logs",
    icon: "FileText",
    path: "/portals/transport/fuel-logs",
    requiredPermissions: [],
    portalType: "school",
    group: "Fleet",
    order: 259,
  },
  {
    id: "transport_maintenance",
    label: "Maintenance",
    icon: "ClipboardList",
    path: "/portals/transport/maintenance",
    requiredPermissions: [],
    portalType: "school",
    group: "Fleet",
    order: 260,
  },
  {
    id: "transport_routes",
    label: "All Routes",
    icon: "Map",
    path: "/portals/transport/all-routes",
    requiredPermissions: [],
    portalType: "school",
    group: "Routes",
    order: 261,
  },
  {
    id: "transport_route_builder",
    label: "Route Builder",
    icon: "Map",
    path: "/portals/transport/route-builder",
    requiredPermissions: [],
    portalType: "school",
    group: "Routes",
    order: 262,
  },
  {
    id: "transport_stop_management",
    label: "Stop Management",
    icon: "MapPinned",
    path: "/portals/transport/stop-management",
    requiredPermissions: [],
    portalType: "school",
    group: "Routes",
    order: 263,
  },
  {
    id: "transport_students",
    label: "Transport Students",
    icon: "Users",
    path: "/portals/transport/transport-students",
    requiredPermissions: [],
    portalType: "school",
    group: "Students",
    order: 264,
  },
  {
    id: "transport_assignments",
    label: "Assign to Route",
    icon: "UserPlus",
    path: "/portals/transport/assign-to-route",
    requiredPermissions: [],
    portalType: "school",
    group: "Students",
    order: 265,
  },
  {
    id: "transport_drivers",
    label: "All Drivers",
    icon: "UserCircle",
    path: "/portals/transport/all-drivers",
    requiredPermissions: [],
    portalType: "school",
    group: "Drivers",
    order: 266,
  },
  {
    id: "transport_take_attendance",
    label: "Take Attendance",
    icon: "ClipboardCheck",
    path: "/portals/transport/take-attendance",
    requiredPermissions: [],
    portalType: "school",
    group: "Attendance",
    order: 267,
  },
  {
    id: "transport_attendance_history",
    label: "Attendance History",
    icon: "FileClock",
    path: "/portals/transport/attendance-history",
    requiredPermissions: [],
    portalType: "school",
    group: "Attendance",
    order: 268,
  },
  {
    id: "transport_log_incident",
    label: "Log Incident",
    icon: "ShieldCheck",
    path: "/portals/transport/log-incident",
    requiredPermissions: [],
    portalType: "school",
    group: "Incidents",
    order: 269,
  },
  {
    id: "transport_incident_log",
    label: "Incident Log",
    icon: "FileText",
    path: "/portals/transport/incident-log",
    requiredPermissions: [],
    portalType: "school",
    group: "Incidents",
    order: 270,
  },
  {
    id: "transport_route_report",
    label: "Route Report",
    icon: "BarChart3",
    path: "/portals/transport/route-report",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 271,
  },
  {
    id: "transport_fuel_report",
    label: "Fuel Report",
    icon: "BarChart3",
    path: "/portals/transport/fuel-report",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 272,
  },
  {
    id: "transport_maintenance_report",
    label: "Maintenance Report",
    icon: "BarChart3",
    path: "/portals/transport/maintenance-report",
    requiredPermissions: [],
    portalType: "school",
    group: "Reports",
    order: 273,
  },
  {
    id: "transport_send_alert",
    label: "Send Alert to Parents",
    icon: "Megaphone",
    path: "/portals/transport/send-alert-to-parents",
    requiredPermissions: [],
    portalType: "school",
    group: "Alerts",
    order: 274,
  },
  {
    id: "transport_profile",
    label: "Profile",
    icon: "User",
    path: "/portals/transport/profile",
    requiredPermissions: [],
    portalType: "school",
    group: "Overview",
    hideFromSidebar: true,
    order: 274.5,
  },
];

const portalGroupsByRole: Partial<Record<Role, NavigationGroup>> = {
  STUDENT: "Student Portal",
  PARENT: "Parent Portal",
  TEACHER: "Teacher Portal",
  CLASS_TEACHER: "Teacher Portal",
  SUBJECT_TEACHER: "Teacher Portal",
  ADMISSIONS_OFFICER: "Admissions Portal",
  EXAM_OFFICER: "Exam Portal",
  EXAMINATION_OFFICER: "Exam Portal",
};

const portalOnlyRoles = new Set<Role>(["STUDENT", "PARENT", "TEACHER", "CLASS_TEACHER", "SUBJECT_TEACHER", "ADMISSIONS_OFFICER", "EXAM_OFFICER", "EXAMINATION_OFFICER"]);
const teacherPortalRoles = new Set<Role>(["TEACHER", "CLASS_TEACHER", "SUBJECT_TEACHER"]);
const nursePortalRoles = new Set<Role>(["SCHOOL_NURSE", "NURSE"]);
const librarianPortalRoles = new Set<Role>(["LIBRARIAN"]);
const frontDeskPortalRoles = new Set<Role>(["RECEPTIONIST"]);
const hostelPortalRoles = new Set<Role>(["HOSTEL_MANAGER", "HOSTEL_MASTER", "HOSTEL_MATRON", "HOSTEL_MISTRESS"]);
const transportPortalRoles = new Set<Role>(["TRANSPORT_COORDINATOR", "TRANSPORT_MANAGER"]);
const financeOnlyRoles = new Set<Role>(["BURSAR", "ACCOUNTANT", "ACCOUNT_OFFICER"]);
const personalPortalGroups = new Set<NavigationGroup>([
  "Student Portal",
  "Parent Portal",
  "Teacher Portal",
  "Admissions Portal",
  "Exam Portal",
]);

export const platformRoles: Role[] = [
  "PLATFORM_OWNER",
  "PLATFORM_ADMIN",
  "SUPPORT_AGENT",
  "SALES_MANAGER",
  "FINANCE_MANAGER",
  "DEVELOPER",
  "SUPER_ADMIN",
];

export function isPlatformRole(role: Role) {
  return platformRoles.includes(role);
}

export function getDefaultPermissionsForRole(role: Role) {
  if (isPlatformRole(role)) return platformPermissionByRole[role] ?? [];
  return systemRolePermissionKeys[role] ?? [];
}

function permissionMatches(granted: Set<string>, required: string) {
  if (granted.has(required)) return true;
  const [namespace] = required.split(".");
  return granted.has(`${namespace}.*`) || granted.has("sa.*");
}

export function canAccessNavItem(
  item: NavigationRegistryItem,
  permissions: string[],
) {
  if (item.requiredPermissions.length === 0) return true;
  const granted = new Set(permissions);
  if (item.requireAny)
    return item.requiredPermissions.some((permission) =>
      permissionMatches(granted, permission),
    );
  return item.requiredPermissions.every((permission) =>
    permissionMatches(granted, permission),
  );
}

function canUseNavigationItemForRole(
  role: Role,
  item: NavigationRegistryItem,
  permissions: string[],
) {
  if (item.portalType === "super_admin")
    return isPlatformRole(role) && canAccessNavItem(item, permissions);
  if (item.portalType === "school" && isPlatformRole(role)) return false;

  if (item.path.startsWith("/portals/principal")) {
    return role === "PRINCIPAL" && canAccessNavItem(item, permissions);
  }
  if (item.path.startsWith("/portals/student")) {
    return role === "STUDENT" && canAccessNavItem(item, permissions);
  }
  if (item.path.startsWith("/portals/parent")) {
    return role === "PARENT" && canAccessNavItem(item, permissions);
  }
  if (item.path.startsWith("/portals/admission-officer")) {
    return role === "ADMISSIONS_OFFICER" && canAccessNavItem(item, permissions);
  }
  if (item.path.startsWith("/portals/exam-officer")) {
    return (role === "EXAM_OFFICER" || role === "EXAMINATION_OFFICER") && canAccessNavItem(item, permissions);
  }
  if (item.path.startsWith("/portals/teacher")) {
    return teacherPortalRoles.has(role) && canAccessNavItem(item, permissions);
  }
  if (item.path.startsWith("/portals/nurse")) {
    return nursePortalRoles.has(role) && canAccessNavItem(item, permissions);
  }
  if (item.path.startsWith("/portals/librarian")) {
    return librarianPortalRoles.has(role) && canAccessNavItem(item, permissions);
  }
  if (item.path.startsWith("/portals/front-desk")) {
    return frontDeskPortalRoles.has(role) && canAccessNavItem(item, permissions);
  }
  if (item.path.startsWith("/portals/hostel")) {
    return hostelPortalRoles.has(role) && canAccessNavItem(item, permissions);
  }
  if (item.path.startsWith("/portals/transport")) {
    return transportPortalRoles.has(role) && canAccessNavItem(item, permissions);
  }
  if (item.id === "teacher_subjects_legacy") {
    return teacherPortalRoles.has(role) && canAccessNavItem(item, permissions);
  }
  const portalGroup = portalGroupsByRole[role];
  if (teacherPortalRoles.has(role)) {
    const teacherAllowed =
      item.path.startsWith("/portals/teacher") || item.id === "teacher_subjects_legacy";
    return teacherAllowed && canAccessNavItem(item, permissions);
  }
  if (portalOnlyRoles.has(role))
    return item.group === portalGroup && canAccessNavItem(item, permissions);
  if (financeOnlyRoles.has(role)) {
    const financeAllowed =
      item.group === "Finance" ||
      item.id === "profile" ||
      item.id === "my_permissions";
    return financeAllowed && canAccessNavItem(item, permissions);
  }
  if (item.group === "Student Portal" || item.group === "Parent Portal" || item.group === "Exam Portal")
    return false;
  if (item.group === "Teacher Portal")
    return item.group === portalGroup && canAccessNavItem(item, permissions);

  return canAccessNavItem(item, permissions);
}

export function getNavigationItemForPath(path: string) {
  return NAV_REGISTRY.filter(
    (item) => path === item.path || path.startsWith(`${item.path}/`),
  ).sort((left, right) => right.path.length - left.path.length)[0];
}

function getNavigationItemsForPath(path: string) {
  const matches = NAV_REGISTRY.filter(
    (item) => path === item.path || path.startsWith(`${item.path}/`),
  ).sort((left, right) => right.path.length - left.path.length);
  const longestPathLength = matches[0]?.path.length;
  return longestPathLength
    ? matches.filter((item) => item.path.length === longestPathLength)
    : [];
}

export function canAccessPathWithPermissions(
  role: Role,
  path: string,
  permissions = getDefaultPermissionsForRole(role),
) {
  const items = getNavigationItemsForPath(path);
  if (!items.length) return false;
  return items.some((item) =>
    canUseNavigationItemForRole(role, item, permissions),
  );
}

export function buildNavigation(
  portalType: PortalType,
  role: Role,
  permissions = getDefaultPermissionsForRole(role),
) {
  const items = NAV_REGISTRY.filter((item) => item.portalType === portalType)
    .filter((item) => {
      if (role === "PRINCIPAL" && portalType === "school") {
        return item.path.startsWith("/portals/principal");
      }
      if (nursePortalRoles.has(role) && portalType === "school") {
        return item.path.startsWith("/portals/nurse");
      }
      if (librarianPortalRoles.has(role) && portalType === "school") {
        return item.path.startsWith("/portals/librarian");
      }
      if (frontDeskPortalRoles.has(role) && portalType === "school") {
        return item.path.startsWith("/portals/front-desk");
      }
      if (hostelPortalRoles.has(role) && portalType === "school") {
        return item.path.startsWith("/portals/hostel");
      }
      if (transportPortalRoles.has(role) && portalType === "school") {
        return item.path.startsWith("/portals/transport");
      }
      return true;
    })
    .filter((item) => {
      if (portalType === "super_admin") return isPlatformRole(role);
      return (
        !item.group ||
        !personalPortalGroups.has(item.group) ||
        Boolean(portalGroupsByRole[role])
      );
    })
    .filter((item) => !item.hideFromSidebar)
    .filter((item) => canUseNavigationItemForRole(role, item, permissions))
    .sort((left, right) => left.order - right.order);

  const groups = new Map<string, NavigationRegistryItem[]>();
  for (const item of items) {
    const group = item.group ?? "Start Here";
    groups.set(group, [...(groups.get(group) ?? []), item]);
  }

  return Array.from(groups.entries()).map(([title, groupItems]) => ({
    title,
    items: groupItems,
  }));
}
